APM:Libraries: AC_Avoid Class Reference
AC_Avoid Class Reference
#include <AC_Avoid.h>
Public Member Functions
AC_Avoid (const AP_AHRS &ahrs, const AP_InertialNav &inav, const AC_Fence &fence, const AP_Proximity &proximity, const AP_Beacon *beacon=nullptr)
Constructor.
void adjust_velocity (float kP, float accel_cmss, Vector2f &desired_vel)
void adjust_velocity (float kP, float accel_cmss, Vector3f &desired_vel)
void adjust_velocity_z (float kP, float accel_cmss, float &climb_rate_cms)
void adjust_roll_pitch (float &roll, float &pitch, float angle_max)
void proximity_avoidance_enable (bool on_off)
bool proximity_avoidance_enabled ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void adjust_velocity_circle_fence (float kP, float accel_cmss, Vector2f &desired_vel)
void adjust_velocity_polygon_fence (float kP, float accel_cmss, Vector2f &desired_vel)
void adjust_velocity_beacon_fence (float kP, float accel_cmss, Vector2f &desired_vel)
void adjust_velocity_proximity (float kP, float accel_cmss, Vector2f &desired_vel)
void adjust_velocity_polygon (float kP, float accel_cmss, Vector2f &desired_vel, const Vector2f *boundary, uint16_t num_points, bool earth_frame, float margin)
void limit_velocity (float kP, float accel_cmss, Vector2f &desired_vel, const Vector2f &limit_direction, float limit_distance) const
Vector2f get_position () const
float get_alt_above_home () const
float get_max_speed (float kP, float accel_cmss, float distance) const
float get_stopping_distance (float kP, float accel_cmss, float speed) const
float distance_to_lean_pct (float dist_m)
void get_proximity_roll_pitch_pct (float &roll_positive, float &roll_negative, float &pitch_positive, float &pitch_negative)
Private Attributes
const AP_AHRS & _ahrs
const AP_InertialNav & _inav
const AC_Fence & _fence
const AP_Proximity & _proximity
const AP_Beacon * _beacon
AP_Int8 _enabled
AP_Int16 _angle_max
AP_Float _dist_max
AP_Float _margin
bool _proximity_enabled = true
Detailed Description
Definition at line 30 of file AC_Avoid.h.
Constructor & Destructor Documentation
AC_Avoid::AC_Avoid (const AP_AHRS & ahrs, const AP_InertialNav & inav, const AC_Fence & fence, const AP_Proximity & proximity, const AP_Beacon * beacon = nullptr)
Constructor.
Definition at line 41 of file AC_Avoid.cpp.
Member Function Documentation
void AC_Avoid::adjust_roll_pitch (float & roll, float & pitch, float angle_max)
Definition at line 147 of file AC_Avoid.cpp.
void AC_Avoid::adjust_velocity (float kP, float accel_cmss, Vector2f & desired_vel)
Definition at line 51 of file AC_Avoid.cpp.
Referenced by adjust_velocity(), and AC_WPNav::calc_loiter_desired_velocity().
void AC_Avoid::adjust_velocity (float kP, float accel_cmss, Vector3f & desired_vel)
Definition at line 76 of file AC_Avoid.cpp.
void AC_Avoid::adjust_velocity_beacon_fence (float kP, float accel_cmss, Vector2f & desired_vel) private
Definition at line 266 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
void AC_Avoid::adjust_velocity_circle_fence (float kP, float accel_cmss, Vector2f & desired_vel) private
Definition at line 196 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
void AC_Avoid::adjust_velocity_polygon (float kP, float accel_cmss, Vector2f & desired_vel, const Vector2f * boundary, uint16_t num_points, bool earth_frame, float margin) private
Definition at line 313 of file AC_Avoid.cpp.
Referenced by adjust_velocity_beacon_fence(), adjust_velocity_polygon_fence(), and adjust_velocity_proximity().
void AC_Avoid::adjust_velocity_polygon_fence (float kP, float accel_cmss, Vector2f & desired_vel) private
Definition at line 237 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
void AC_Avoid::adjust_velocity_proximity (float kP, float accel_cmss, Vector2f & desired_vel) private
Definition at line 292 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
void AC_Avoid::adjust_velocity_z (float kP, float accel_cmss, float & climb_rate_cms)
Definition at line 85 of file AC_Avoid.cpp.
float AC_Avoid::distance_to_lean_pct (float dist_m) private
Definition at line 445 of file AC_Avoid.cpp.
Referenced by get_proximity_roll_pitch_pct().
float AC_Avoid::get_alt_above_home () const private
Definition at line 407 of file AC_Avoid.cpp.
Referenced by adjust_velocity_z().
float AC_Avoid::get_max_speed (float kP, float accel_cmss, float distance) const private
Definition at line 417 of file AC_Avoid.cpp.
Referenced by adjust_velocity_circle_fence(), adjust_velocity_z(), and limit_velocity().
Vector2f AC_Avoid::get_position () const private
Definition at line 396 of file AC_Avoid.cpp.
Referenced by adjust_velocity_circle_fence().
void AC_Avoid::get_proximity_roll_pitch_pct (float & roll_positive, float & roll_negative, float & pitch_positive, float & pitch_negative) private
Definition at line 456 of file AC_Avoid.cpp.
Referenced by adjust_roll_pitch().
float AC_Avoid::get_stopping_distance (float kP, float accel_cmss, float speed) const private
Definition at line 427 of file AC_Avoid.cpp.
Referenced by adjust_velocity_circle_fence().
void AC_Avoid::limit_velocity (float kP, float accel_cmss, Vector2f & desired_vel, const Vector2f & limit_direction, float limit_distance) const private
Definition at line 382 of file AC_Avoid.cpp.
Referenced by adjust_velocity_polygon().
void AC_Avoid::proximity_avoidance_enable (bool on_off) inline
Definition at line 53 of file AC_Avoid.h.
bool AC_Avoid::proximity_avoidance_enabled () inline
Definition at line 54 of file AC_Avoid.h.
Member Data Documentation
const AP_AHRS& AC_Avoid::_ahrs private
Definition at line 124 of file AC_Avoid.h.
Referenced by adjust_velocity_polygon(), get_alt_above_home(), and get_position().
AP_Int16 AC_Avoid::_angle_max private
Definition at line 132 of file AC_Avoid.h.
Referenced by adjust_roll_pitch().
const AP_Beacon* AC_Avoid::_beacon private
Definition at line 128 of file AC_Avoid.h.
Referenced by adjust_velocity_beacon_fence().
AP_Float AC_Avoid::_dist_max private
Definition at line 133 of file AC_Avoid.h.
Referenced by distance_to_lean_pct(), and get_proximity_roll_pitch_pct().
AP_Int8 AC_Avoid::_enabled private
Definition at line 131 of file AC_Avoid.h.
Referenced by adjust_roll_pitch(), adjust_velocity(), and adjust_velocity_z().
const AC_Fence& AC_Avoid::_fence private
Definition at line 126 of file AC_Avoid.h.
Referenced by adjust_velocity_beacon_fence(), adjust_velocity_circle_fence(), adjust_velocity_polygon(), adjust_velocity_polygon_fence(), and adjust_velocity_z().
const AP_InertialNav& AC_Avoid::_inav private
Definition at line 125 of file AC_Avoid.h.
Referenced by adjust_velocity_polygon(), adjust_velocity_z(), get_alt_above_home(), and get_position().
AP_Float AC_Avoid::_margin private
Definition at line 134 of file AC_Avoid.h.
Referenced by adjust_velocity_proximity(), and adjust_velocity_z().
const AP_Proximity& AC_Avoid::_proximity private
Definition at line 127 of file AC_Avoid.h.
Referenced by adjust_velocity_proximity(), adjust_velocity_z(), and get_proximity_roll_pitch_pct().
bool AC_Avoid::_proximity_enabled = true private
Definition at line 136 of file AC_Avoid.h.
Referenced by adjust_roll_pitch(), adjust_velocity(), proximity_avoidance_enable(), and proximity_avoidance_enabled().
const AP_Param::GroupInfo AC_Avoid::var_info static
Definition at line 56 of file AC_Avoid.h.
Referenced by AC_Avoid().
The documentation for this class was generated from the following files:
libraries/AC_Avoidance/AC_Avoid.h
libraries/AC_Avoidance/AC_Avoid.cpp