APM:Libraries: DataFlash_Class Class Reference
DataFlash_Class Class Reference
#include <DataFlash.h>
Classes
struct log_write_fmt
struct PID_Info
Public Member Functions
FUNCTOR_TYPEDEF (print_mode_fn, void, AP_HAL::BetterStream *, uint8_t)
FUNCTOR_TYPEDEF (vehicle_startup_message_Log_Writer, void)
DataFlash_Class (const char *firmware_string, const AP_Int32 &log_bitmask)
void set_mission (const AP_Mission *mission)
void Init (const struct LogStructure *structure, uint8_t num_types)
bool CardInserted (void)
bool NeedErase (void)
void EraseAll ()
const struct LogStructure * get_structures (uint8_t &num_types)
void WriteBlock (const void *pBuffer, uint16_t size)
void WriteCriticalBlock (const void *pBuffer, uint16_t size)
uint16_t find_last_log () const
void get_log_boundaries (uint16_t log_num, uint16_t &start_page, uint16_t &end_page)
int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
uint16_t get_num_logs (void)
void LogReadProcess (uint16_t log_num, uint16_t start_page, uint16_t end_page, print_mode_fn printMode, AP_HAL::BetterStream *port)
void DumpPageInfo (AP_HAL::BetterStream *port)
void ShowDeviceInfo (AP_HAL::BetterStream *port)
void ListAvailableLogs (AP_HAL::BetterStream *port)
void setVehicle_Startup_Log_Writer (vehicle_startup_message_Log_Writer writer)
void PrepForArming ()
void EnableWrites (bool enable)
bool WritesEnabled () const
void StopLogging ()
void Log_Write_Parameter (const char *name, float value)
void Log_Write_GPS (const AP_GPS &gps, uint8_t instance, uint64_t time_us=0)
void Log_Write_RFND (const RangeFinder &rangefinder)
void Log_Write_IMU (const AP_InertialSensor &ins)
void Log_Write_IMUDT (const AP_InertialSensor &ins, uint64_t time_us, uint8_t imu_mask)
void Log_Write_Vibration (const AP_InertialSensor &ins)
void Log_Write_RCIN (void)
void Log_Write_RCOUT (void)
void Log_Write_RSSI (AP_RSSI &rssi)
void Log_Write_Baro (AP_Baro &baro, uint64_t time_us=0)
void Log_Write_Power (void)
void Log_Write_AHRS2 (AP_AHRS &ahrs)
void Log_Write_POS (AP_AHRS &ahrs)
bool Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t &mav_cmd)
void Log_Write_Radio (const mavlink_radio_t &packet)
void Log_Write_Message (const char *message)
void Log_Write_MessageF (const char *fmt,...)
void Log_Write_CameraInfo (enum LogMessages msg, const AP_AHRS &ahrs, const AP_GPS &gps, const Location &current_loc)
void Log_Write_Camera (const AP_AHRS &ahrs, const AP_GPS &gps, const Location &current_loc)
void Log_Write_Trigger (const AP_AHRS &ahrs, const AP_GPS &gps, const Location &current_loc)
void Log_Write_ESC (void)
void Log_Write_Airspeed (AP_Airspeed &airspeed)
void Log_Write_Attitude (AP_AHRS &ahrs, const Vector3f &targets)
void Log_Write_AttitudeView (AP_AHRS_View &ahrs, const Vector3f &targets)
void Log_Write_Current (const AP_BattMonitor &battery)
void Log_Write_Compass (const Compass &compass, uint64_t time_us=0)
void Log_Write_Mode (uint8_t mode, uint8_t reason=0)
void Log_Write_EntireMission (const AP_Mission &mission)
void Log_Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
void Log_Write_Origin (uint8_t origin_type, const Location &loc)
void Log_Write_RPM (const AP_RPM &rpm_sensor)
void Log_Write_Rate (const AP_AHRS &ahrs, const AP_Motors &motors, const AC_AttitudeControl &attitude_control, const AC_PosControl &pos_control)
void Log_Write_Rally (const AP_Rally &rally)
void Log_Write_VisualOdom (float time_delta, const Vector3f &angle_delta, const Vector3f &position_delta, float confidence)
void Log_Write_AOA_SSA (AP_AHRS &ahrs)
void Log_Write_Beacon (AP_Beacon &beacon)
void Log_Write_Proximity (AP_Proximity &proximity)
void Log_Write (const char *name, const char *labels, const char *fmt,...)
void Log_Write_PID (uint8_t msg_type, const PID_Info &info)
bool should_log (uint32_t mask) const
bool logging_started (void)
void flush (void)
void handle_mavlink_msg (class GCS_MAVLINK &, mavlink_message_t *msg)
void periodic_tasks ()
uint32_t num_dropped (void) const
bool log_while_disarmed (void) const
uint8_t log_replay (void) const
const struct LogStructure * structure (uint16_t num) const
bool logging_present () const
bool logging_enabled () const
bool logging_failed () const
void set_vehicle_armed (bool armed_state)
bool vehicle_is_armed () const
void handle_log_send (class GCS_MAVLINK &)
bool in_log_download () const
Static Public Member Functions
static DataFlash_Class * instance (void)
Public Attributes
vehicle_startup_message_Log_Writer _vehicle_messages
struct {
AP_Int8 backend_types
AP_Int8 file_bufsize
AP_Int8 file_disarm_rot
AP_Int8 log_disarmed
AP_Int8 log_replay
} _params
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)
Protected Attributes
const struct LogStructure * _structures
uint8_t _num_types
Private Member Functions
void internal_error () const
struct log_write_fmt * msg_fmt_for_name (const char *name, const char *labels, const char *fmt)
bool msg_type_in_use (uint8_t msg_type) const
int16_t find_free_msg_type () const
bool fill_log_write_logstructure (struct LogStructure &logstruct, const uint8_t msg_type) const
int16_t Log_Write_calc_msg_len (const char *fmt) const
void backend_starting_new_log (const DataFlash_Backend *backend)
void validate_structures (const struct LogStructure *logstructures, const uint8_t num_types)
void dump_structure_field (const struct LogStructure *logstructure, const char *label, const uint8_t fieldnum)
pretty-print field information from a log structure
void dump_structures (const struct LogStructure *logstructures, const uint8_t num_types)
void Log_Write_EKF_Timing (const char *name, uint64_t time_us, const struct ekf_timing &timing)
void Prep ()
bool should_handle_log_message ()
void handle_log_message (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_request_list (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_request_data (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_request_erase (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_request_end (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_send_listing (class GCS_MAVLINK &)
bool handle_log_send_data (class GCS_MAVLINK &)
void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)
Private Attributes
uint8_t _next_backend
DataFlash_Backend * backends [DATAFLASH_MAX_BACKENDS]
const char * _firmware_string
const AP_Int32 & _log_bitmask
struct DataFlash_Class::log_write_fmt * log_write_fmts
bool _armed
bool _writes_enabled
uint8_t _log_listing:1
uint8_t _log_sending:1
bool _in_log_download:1
uint16_t _log_next_list_entry
uint16_t _log_last_list_entry
uint16_t _log_num_logs
uint16_t _log_num_data
uint32_t _log_data_offset
uint32_t _log_data_size
uint32_t _log_data_remaining
uint16_t _log_data_page
int8_t _log_sending_chan = -1
Static Private Attributes
static DataFlash_Class * _instance
Friends
class DataFlash_Backend
Detailed Description
Definition at line 46 of file DataFlash.h.
Constructor & Destructor Documentation
DataFlash_Class::DataFlash_Class (const char * firmware_string, const AP_Int32 & log_bitmask) inline
Definition at line 53 of file DataFlash.h.
Member Function Documentation
void DataFlash_Class::backend_starting_new_log (const DataFlash_Backend * backend) private
Definition at line 286 of file DataFlash.cpp.
Referenced by DataFlash_Backend::start_new_log_reset_variables().
bool DataFlash_Class::CardInserted (void)
Definition at line 372 of file DataFlash.cpp.
Referenced by instance().
void DataFlash_Class::dump_structure_field (const struct LogStructure * logstructure, const char * label, const uint8_t fieldnum) private
pretty-print field information from a log structure
Definition at line 138 of file DataFlash.cpp.
Referenced by dump_structures(), and validate_structures().
void DataFlash_Class::dump_structures (const struct LogStructure * logstructures, const uint8_t num_types) private
pretty-print log structures
Note
structures MUST be well-formed
Definition at line 145 of file DataFlash.cpp.
Referenced by Init(), and validate_structures().
void DataFlash_Class::DumpPageInfo (AP_HAL::BetterStream * port)
Definition at line 431 of file DataFlash.cpp.
Referenced by get_structures().
void DataFlash_Class::EnableWrites (bool enable) inline
Definition at line 107 of file DataFlash.h.
Referenced by Init().
void DataFlash_Class::EraseAll ()
Definition at line 368 of file DataFlash.cpp.
Referenced by handle_log_request_erase(), and instance().
bool DataFlash_Class::fill_log_write_logstructure (struct LogStructure & logstruct, const uint8_t msg_type) const private
Definition at line 637 of file DataFlash.cpp.
Referenced by DataFlash_Backend::Log_Write_Emit_FMT().
int16_t DataFlash_Class::find_free_msg_type () const private
Definition at line 626 of file DataFlash.cpp.
Referenced by msg_fmt_for_name().
uint16_t DataFlash_Class::find_last_log () const
Definition at line 390 of file DataFlash.cpp.
Referenced by get_structures().
void DataFlash_Class::flush (void)
Definition at line 487 of file DataFlash.cpp.
Referenced by DataFlashTest_AllTypes::flush_dataflash().
DataFlash_Class::FUNCTOR_TYPEDEF (print_mode_fn , void , AP_HAL::BetterStream * , uint8_t)
DataFlash_Class::FUNCTOR_TYPEDEF (vehicle_startup_message_Log_Writer , void)
void DataFlash_Class::get_log_boundaries (uint16_t log_num, uint16_t & start_page, uint16_t & end_page)
Definition at line 396 of file DataFlash.cpp.
Referenced by get_structures(), and handle_log_request_data().
int16_t DataFlash_Class::get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data)
Definition at line 408 of file DataFlash.cpp.
Referenced by get_structures(), and handle_log_send_data().
void DataFlash_Class::get_log_info (uint16_t log_num, uint32_t & size, uint32_t & time_utc) private
Definition at line 402 of file DataFlash.cpp.
Referenced by handle_log_request_data(), and handle_log_send_listing().
uint16_t DataFlash_Class::get_num_logs (void)
Definition at line 414 of file DataFlash.cpp.
Referenced by get_structures(), handle_log_request_data(), and handle_log_request_list().
const struct LogStructure* DataFlash_Class::get_structures (uint8_t & num_types) inline
Definition at line 80 of file DataFlash.h.
void DataFlash_Class::handle_log_message (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle all types of log download requests from the GCS
Definition at line 43 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_mavlink_msg().
void DataFlash_Class::handle_log_request_data (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle request for log data
Definition at line 105 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
void DataFlash_Class::handle_log_request_end (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle request to stop transfer and resume normal logging
Definition at line 170 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
void DataFlash_Class::handle_log_request_erase (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle request to erase log data
Definition at line 159 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
void DataFlash_Class::handle_log_request_list (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle all types of log download requests from the GCS
Definition at line 67 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
void DataFlash_Class::handle_log_send (class GCS_MAVLINK & link)
trigger sending of log messages if there are some pending
Definition at line 182 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_log_request_data(), and vehicle_is_armed().
bool DataFlash_Class::handle_log_send_data (class GCS_MAVLINK & link) private
trigger sending of log data if there are some pending
Definition at line 251 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_log_send().
void DataFlash_Class::handle_log_send_listing (class GCS_MAVLINK & link) private
trigger sending of log messages if there are some pending
Definition at line 221 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_log_request_list(), and handle_log_send().
void DataFlash_Class::handle_mavlink_msg (class GCS_MAVLINK & link, mavlink_message_t * msg)
Definition at line 463 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_common_message().
bool DataFlash_Class::in_log_download () const inline
Definition at line 218 of file DataFlash.h.
Referenced by should_log(), and DataFlash_Backend::StartNewLogOK().
void DataFlash_Class::Init (const struct LogStructure * structure, uint8_t num_types)
Definition at line 51 of file DataFlash.cpp.
Referenced by instance().
static DataFlash_Class* DataFlash_Class::instance (void) inline static
Definition at line 65 of file DataFlash.h.
Referenced by AP_Compass_MMC3416::accumulate_field(), AP_Arming::arm_checks(), NavEKF3::check_log_write(), NavEKF2::check_log_write(), AC_AttitudeControl::control_monitor_log(), AP_InertialSensor_Backend::get_dataflash(), GCS_MAVLINK::handle_common_message(), GCS_MAVLINK::handle_common_mission_message(), GCS_MAVLINK::handle_statustext(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), AP_GPS_SBF::log_ExtEventPVTGeodetic(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_Camera::log_picture(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), AP_Tuning::Log_Write_Parameter_Tuning(), AP_Arming::logging_checks(), AP_GPS_SBP2::logging_ext_event(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP2::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), AP_GPS_SBP2::logging_log_raw_sbp(), GCS_MAVLINK::send_parameter_value_all(), AP_GPS_Backend::should_df_log(), SITL::Aircraft::smooth_sensors(), AP_Compass_MMC3416::timer(), AP_Landing::type_slope_log(), Variometer::update(), AP_TECS::update_pitch_throttle(), SITL::Aircraft::update_position(), SoaringController::update_thermalling(), AP_Camera::update_trigger(), AP_GPS_Backend::Write_DataFlash_Log_Startup_messages(), AP_GPS_UBLOX::Write_DataFlash_Log_Startup_messages(), and WritesEnabled().
void DataFlash_Class::internal_error () const private
Definition at line 530 of file DataFlash.cpp.
Referenced by Log_Write().
void DataFlash_Class::ListAvailableLogs (AP_HAL::BetterStream * port)
Definition at line 445 of file DataFlash.cpp.
Referenced by get_structures().
uint8_t DataFlash_Class::log_replay (void) const inline
Definition at line 191 of file DataFlash.h.
bool DataFlash_Class::log_while_disarmed (void) const inline
Definition at line 190 of file DataFlash.h.
Referenced by should_log(), and DataFlash_Backend::ShouldLog().
void DataFlash_Class::Log_Write (const char * name, const char * labels, const char * fmt, ...)
Definition at line 538 of file DataFlash.cpp.
Referenced by AP_Compass_MMC3416::accumulate_field(), AC_AttitudeControl::control_monitor_log(), AP_Tuning::Log_Write_Parameter_Tuning(), SITL::Aircraft::smooth_sensors(), AP_Compass_MMC3416::timer(), AP_Landing::type_slope_log(), Variometer::update(), AP_TECS::update_pitch_throttle(), SITL::Aircraft::update_position(), SoaringController::update_thermalling(), and WritesEnabled().
void DataFlash_Class::Log_Write_AHRS2 (AP_AHRS & ahrs)
Definition at line 635 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Airspeed (AP_Airspeed & airspeed)
Definition at line 1767 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_AOA_SSA (AP_AHRS & ahrs)
Definition at line 1893 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Attitude (AP_AHRS & ahrs, const Vector3f & targets)
Definition at line 1538 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_AttitudeView (AP_AHRS_View & ahrs, const Vector3f & targets)
Definition at line 1556 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Baro (AP_Baro & baro, uint64_t time_us = 0)
Definition at line 365 of file LogFile.cpp.
Referenced by NavEKF3::check_log_write(), NavEKF2::check_log_write(), and WritesEnabled().
void DataFlash_Class::Log_Write_Beacon (AP_Beacon & beacon)
Definition at line 1906 of file LogFile.cpp.
Referenced by WritesEnabled().
int16_t DataFlash_Class::Log_Write_calc_msg_len (const char * fmt) const private
Definition at line 663 of file DataFlash.cpp.
Referenced by msg_fmt_for_name(), and validate_structures().
void DataFlash_Class::Log_Write_Camera (const AP_AHRS & ahrs, const AP_GPS & gps, const Location & current_loc)
Definition at line 1526 of file LogFile.cpp.
Referenced by AP_Camera::log_picture(), AP_Camera::update_trigger(), and WritesEnabled().
void DataFlash_Class::Log_Write_CameraInfo (enum LogMessages msg, const AP_AHRS & ahrs, const AP_GPS & gps, const Location & current_loc)
Definition at line 1492 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Compass (const Compass & compass, uint64_t time_us = 0)
Definition at line 1642 of file LogFile.cpp.
Referenced by NavEKF3::check_log_write(), NavEKF2::check_log_write(), and WritesEnabled().
void DataFlash_Class::Log_Write_Current (const AP_BattMonitor & battery)
Definition at line 1574 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_EKF_Timing (const char * name, uint64_t time_us, const struct ekf_timing & timing) private
Referenced by Log_Write_POS().
void DataFlash_Class::Log_Write_EntireMission (const AP_Mission & mission)
Definition at line 493 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_common_mission_message(), and WritesEnabled().
void DataFlash_Class::Log_Write_ESC (void)
Definition at line 1726 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_GPS (const AP_GPS & gps, uint8_t instance, uint64_t time_us = 0)
Definition at line 247 of file LogFile.cpp.
Referenced by NavEKF3::check_log_write(), NavEKF2::check_log_write(), and WritesEnabled().
void DataFlash_Class::Log_Write_IMU (const AP_InertialSensor & ins)
Definition at line 418 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_IMUDT (const AP_InertialSensor & ins, uint64_t time_us, uint8_t imu_mask)
Definition at line 491 of file LogFile.cpp.
Referenced by NavEKF3::check_log_write(), NavEKF2::check_log_write(), and WritesEnabled().
bool DataFlash_Class::Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t & mav_cmd)
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Message (const char * message)
Definition at line 498 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_statustext(), Log_Write_MessageF(), AP_GPS_Backend::Write_DataFlash_Log_Startup_messages(), and WritesEnabled().
void DataFlash_Class::Log_Write_MessageF (const char * fmt, ...)
Definition at line 274 of file DataFlash.cpp.
Referenced by AP_GPS_UBLOX::Write_DataFlash_Log_Startup_messages(), and WritesEnabled().
void DataFlash_Class::Log_Write_Mission_Cmd (const AP_Mission & mission, const AP_Mission::Mission_Command & cmd)
Definition at line 513 of file DataFlash.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Mode (uint8_t mode, uint8_t reason = 0)
Definition at line 503 of file DataFlash.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Origin (uint8_t origin_type, const Location & loc)
Definition at line 1802 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Parameter (const char * name, float value)
Definition at line 508 of file DataFlash.cpp.
Referenced by GCS_MAVLINK::handle_param_set(), SoloGimbal_Parameters::handle_param_value(), AP_AutoTune::log_param_change(), GCS_MAVLINK::send_parameter_value_all(), and WritesEnabled().
void DataFlash_Class::Log_Write_PID (uint8_t msg_type, const PID_Info & info)
Definition at line 1787 of file LogFile.cpp.
void DataFlash_Class::Log_Write_POS (AP_AHRS & ahrs)
Definition at line 662 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Power (void)
Definition at line 620 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Proximity (AP_Proximity & proximity)
Definition at line 1930 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Radio (const mavlink_radio_t & packet)
Definition at line 1475 of file LogFile.cpp.
Referenced by GCS_MAVLINK::handle_radio_status(), and WritesEnabled().
void DataFlash_Class::Log_Write_Rally (const AP_Rally & rally)
Definition at line 1855 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Rate (const AP_AHRS & ahrs, const AP_Motors & motors, const AC_AttitudeControl & attitude_control, const AC_PosControl & pos_control)
Definition at line 1828 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_RCIN (void)
Definition at line 305 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_RCOUT (void)
Definition at line 329 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_RFND (const RangeFinder & rangefinder)
Definition at line 291 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_RPM (const AP_RPM & rpm_sensor)
Definition at line 1816 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_RSSI (AP_RSSI & rssi)
Definition at line 354 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_Trigger (const AP_AHRS & ahrs, const AP_GPS & gps, const Location & current_loc)
Definition at line 1532 of file LogFile.cpp.
Referenced by AP_Camera::log_picture(), and WritesEnabled().
void DataFlash_Class::Log_Write_Vibration (const AP_InertialSensor & ins)
Definition at line 574 of file LogFile.cpp.
Referenced by WritesEnabled().
void DataFlash_Class::Log_Write_VisualOdom (float time_delta, const Vector3f & angle_delta, const Vector3f & position_delta, float confidence)
Definition at line 1875 of file LogFile.cpp.
Referenced by WritesEnabled().
bool DataFlash_Class::logging_enabled () const
Definition at line 248 of file DataFlash.cpp.
bool DataFlash_Class::logging_failed () const
Definition at line 260 of file DataFlash.cpp.
bool DataFlash_Class::logging_present () const
Definition at line 244 of file DataFlash.cpp.
bool DataFlash_Class::logging_started (void)
Definition at line 454 of file DataFlash.cpp.
Referenced by AP_Arming::arm_checks(), AP_AutoTune::log_param_change(), and AP_AutoTune::write_log().
void DataFlash_Class::LogReadProcess (uint16_t log_num, uint16_t start_page, uint16_t end_page, print_mode_fn printMode, AP_HAL::BetterStream * port)
Definition at line 421 of file DataFlash.cpp.
Referenced by get_structures().
DataFlash_Class::log_write_fmt * DataFlash_Class::msg_fmt_for_name (const char * name, const char * labels, const char * fmt) private
Definition at line 564 of file DataFlash.cpp.
Referenced by Log_Write().
bool DataFlash_Class::msg_type_in_use (uint8_t msg_type) const private
Definition at line 605 of file DataFlash.cpp.
Referenced by find_free_msg_type().
bool DataFlash_Class::NeedErase (void)
Referenced by instance().
uint32_t DataFlash_Class::num_dropped (void) const
Definition at line 519 of file DataFlash.cpp.
void DataFlash_Class::periodic_tasks ()
Definition at line 481 of file DataFlash.cpp.
void DataFlash_Class::Prep () private
Definition at line 381 of file DataFlash.cpp.
Referenced by Init().
void DataFlash_Class::PrepForArming ()
Definition at line 324 of file DataFlash.cpp.
Referenced by AP_Arming::arm_checks(), and get_structures().
void DataFlash_Class::set_mission (const AP_Mission * mission)
Definition at line 350 of file DataFlash.cpp.
Referenced by instance().
void DataFlash_Class::set_vehicle_armed (bool armed_state)
Definition at line 334 of file DataFlash.cpp.
void DataFlash_Class::setVehicle_Startup_Log_Writer (vehicle_startup_message_Log_Writer writer)
Definition at line 329 of file DataFlash.cpp.
Referenced by get_structures().
bool DataFlash_Class::should_handle_log_message () private
Definition at line 28 of file DataFlash_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
bool DataFlash_Class::should_log (uint32_t mask) const
Definition at line 299 of file DataFlash.cpp.
Referenced by AP_InertialSensor_Backend::get_dataflash(), AP_Camera::log_picture(), AP_GPS_Backend::should_df_log(), and AP_Camera::update_trigger().
void DataFlash_Class::ShowDeviceInfo (AP_HAL::BetterStream * port)
Definition at line 438 of file DataFlash.cpp.
Referenced by get_structures().
void DataFlash_Class::StopLogging ()
Definition at line 385 of file DataFlash.cpp.
Referenced by WritesEnabled().
const struct LogStructure * DataFlash_Class::structure (uint16_t num) const
Definition at line 239 of file DataFlash.cpp.
Referenced by instance(), msg_type_in_use(), and DataFlash_Backend::structure().
void DataFlash_Class::validate_structures (const struct LogStructure * logstructures, const uint8_t num_types) private
Definition at line 174 of file DataFlash.cpp.
Referenced by Init().
bool DataFlash_Class::vehicle_is_armed () const inline
Definition at line 215 of file DataFlash.h.
Referenced by should_handle_log_message(), should_log(), and DataFlash_Backend::ShouldLog().
void DataFlash_Class::WriteBlock (const void * pBuffer, uint16_t size)
Definition at line 355 of file DataFlash.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), get_structures(), AP_GPS_SBF::log_ExtEventPVTGeodetic(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), SITL::SITL::Log_Write_SIMSTATE(), AP_GPS_SBP2::logging_ext_event(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP2::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), AP_GPS_SBP2::logging_log_raw_sbp(), and AP_AutoTune::write_log().
void DataFlash_Class::WriteCriticalBlock (const void * pBuffer, uint16_t size)
Definition at line 359 of file DataFlash.cpp.
Referenced by get_structures().
void DataFlash_Class::WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical) protected
Definition at line 363 of file DataFlash.cpp.
bool DataFlash_Class::WritesEnabled () const inline
Definition at line 108 of file DataFlash.h.
Referenced by should_handle_log_message(), and DataFlash_Backend::ShouldLog().
Friends And Related Function Documentation
friend class DataFlash_Backend friend
Definition at line 48 of file DataFlash.h.
Member Data Documentation
bool DataFlash_Class::_armed private
Definition at line 274 of file DataFlash.h.
Referenced by set_vehicle_armed(), and vehicle_is_armed().
const char* DataFlash_Class::_firmware_string private
Definition at line 235 of file DataFlash.h.
Referenced by Init().
bool DataFlash_Class::_in_log_download private
Definition at line 302 of file DataFlash.h.
Referenced by handle_log_request_data(), handle_log_request_end(), and in_log_download().
DataFlash_Class * DataFlash_Class::_instance static private
Definition at line 284 of file DataFlash.h.
Referenced by DataFlash_Class(), and instance().
const AP_Int32& DataFlash_Class::_log_bitmask private
Definition at line 236 of file DataFlash.h.
Referenced by should_log(), and DataFlash_Backend::StartNewLogOK().
uint32_t DataFlash_Class::_log_data_offset private
Definition at line 317 of file DataFlash.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
uint16_t DataFlash_Class::_log_data_page private
Definition at line 326 of file DataFlash.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
uint32_t DataFlash_Class::_log_data_remaining private
Definition at line 323 of file DataFlash.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
uint32_t DataFlash_Class::_log_data_size private
Definition at line 320 of file DataFlash.h.
Referenced by handle_log_request_data().
uint16_t DataFlash_Class::_log_last_list_entry private
Definition at line 308 of file DataFlash.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
uint8_t DataFlash_Class::_log_listing private
Definition at line 298 of file DataFlash.h.
Referenced by handle_log_request_data(), handle_log_request_list(), handle_log_send(), and handle_log_send_listing().
uint16_t DataFlash_Class::_log_next_list_entry private
Definition at line 305 of file DataFlash.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
uint16_t DataFlash_Class::_log_num_data private
Definition at line 314 of file DataFlash.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
uint16_t DataFlash_Class::_log_num_logs private
Definition at line 311 of file DataFlash.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
uint8_t DataFlash_Class::_log_sending private
Definition at line 299 of file DataFlash.h.
Referenced by handle_log_request_data(), handle_log_request_end(), handle_log_request_list(), handle_log_send(), and handle_log_send_data().
int8_t DataFlash_Class::_log_sending_chan = -1 private
Definition at line 328 of file DataFlash.h.
Referenced by handle_log_request_data(), handle_log_request_end(), handle_log_request_list(), handle_log_send(), handle_log_send_data(), and handle_log_send_listing().
uint8_t DataFlash_Class::_next_backend private
Definition at line 233 of file DataFlash.h.
Referenced by backend_starting_new_log(), CardInserted(), DumpPageInfo(), find_last_log(), get_log_boundaries(), get_log_data(), get_log_info(), get_num_logs(), Init(), ListAvailableLogs(), Log_Write(), logging_enabled(), logging_failed(), logging_present(), logging_started(), LogReadProcess(), num_dropped(), should_log(), and ShowDeviceInfo().
uint8_t DataFlash_Class::_num_types protected
Definition at line 223 of file DataFlash.h.
Referenced by get_structures(), Init(), msg_type_in_use(), and DataFlash_Backend::num_types().
struct { ... } DataFlash_Class::_params
Referenced by Init(), log_replay(), and log_while_disarmed().
const struct LogStructure* DataFlash_Class::_structures protected
Definition at line 222 of file DataFlash.h.
Referenced by get_structures(), Init(), and structure().
vehicle_startup_message_Log_Writer DataFlash_Class::_vehicle_messages
Definition at line 193 of file DataFlash.h.
Referenced by setVehicle_Startup_Log_Writer(), and DataFlash_Backend::vehicle_message_writer().
bool DataFlash_Class::_writes_enabled private
Definition at line 295 of file DataFlash.h.
Referenced by EnableWrites(), and WritesEnabled().
AP_Int8 DataFlash_Class::backend_types
Definition at line 198 of file DataFlash.h.
DataFlash_Backend* DataFlash_Class::backends[DATAFLASH_MAX_BACKENDS] private
Definition at line 234 of file DataFlash.h.
Referenced by backend_starting_new_log(), CardInserted(), DumpPageInfo(), find_last_log(), get_log_boundaries(), get_log_data(), get_log_info(), get_num_logs(), Init(), ListAvailableLogs(), Log_Write(), logging_enabled(), logging_failed(), logging_started(), LogReadProcess(), num_dropped(), and ShowDeviceInfo().
AP_Int8 DataFlash_Class::file_bufsize
Definition at line 199 of file DataFlash.h.
AP_Int8 DataFlash_Class::file_disarm_rot
Definition at line 200 of file DataFlash.h.
AP_Int8 DataFlash_Class::log_disarmed
Definition at line 201 of file DataFlash.h.
AP_Int8 DataFlash_Class::log_replay
Definition at line 202 of file DataFlash.h.
Referenced by NavEKF3::InitialiseFilter(), and NavEKF2::InitialiseFilter().
struct DataFlash_Class::log_write_fmt * DataFlash_Class::log_write_fmts private
Referenced by backend_starting_new_log(), fill_log_write_logstructure(), DataFlash_Backend::Log_Write(), msg_fmt_for_name(), and msg_type_in_use().
const AP_Param::GroupInfo DataFlash_Class::var_info static
Definition at line 196 of file DataFlash.h.
Referenced by DataFlash_Class().
The documentation for this class was generated from the following files:
libraries/DataFlash/DataFlash.h
libraries/DataFlash/DataFlash.cpp
libraries/DataFlash/DataFlash_MAVLinkLogTransfer.cpp
libraries/DataFlash/LogFile.cpp