APM:Libraries: AP_Camera Class Reference
AP_Camera Class Reference
#include <AP_Camera.h>
Public Member Functions
AP_Camera (AP_Relay *obj_relay, uint32_t _log_camera_bit, const struct Location &_loc, const AP_GPS &_gps, const AP_AHRS &_ahrs)
void control_msg (const mavlink_message_t *msg)
decode deprecated MavLink message that controls camera.
void send_feedback (mavlink_channel_t chan)
void configure (float shooting_mode, float shutter_speed, float aperture, float ISO, float exposure_type, float cmd_id, float engine_cutoff_time)
void control (float session, float zoom_pos, float zoom_step, float focus_lock, float shooting_cmd, float cmd_id)
void set_trigger_distance (uint32_t distance_m)
void take_picture ()
void update ()
void update_trigger ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void servo_pic ()
Servo operated camera.
void relay_pic ()
basic relay activation
void feedback_pin_timer ()
void setup_feedback_callback (void)
void log_picture ()
void trigger_pic ()
void trigger_pic_cleanup ()
bool check_trigger_pin (void)
bool using_feedback_pin (void) const
Static Private Member Functions
static void capture_callback (void *context, uint32_t chan_index, hrt_abstime edge_time, uint32_t edge_state, uint32_t overflow)
Private Attributes
AP_Int8 _trigger_type
AP_Int8 _trigger_duration
AP_Int8 _relay_on
AP_Int16 _servo_on_pwm
AP_Int16 _servo_off_pwm
uint8_t _trigger_counter
AP_Relay * _apm_relay
AP_Float _trigg_dist
AP_Int16 _min_interval
AP_Int16 _max_roll
uint32_t _last_photo_time
struct Location _last_location
uint16_t _image_index
AP_Int8 _feedback_pin
AP_Int8 _feedback_polarity
bool _timer_installed:1
uint8_t _last_pin_state
uint32_t log_camera_bit
const struct Location & current_loc
const AP_GPS & gps
const AP_AHRS & ahrs
Static Private Attributes
static volatile bool _camera_triggered
Detailed Description
Definition at line 31 of file AP_Camera.h.
Constructor & Destructor Documentation
AP_Camera::AP_Camera (AP_Relay * obj_relay, uint32_t _log_camera_bit, const struct Location & _loc, const AP_GPS & _gps, const AP_AHRS & _ahrs) inline
Constructor
Definition at line 36 of file AP_Camera.h.
Member Function Documentation
void AP_Camera::capture_callback (void * context, uint32_t chan_index, hrt_abstime edge_time, uint32_t edge_state, uint32_t overflow) static private
Definition at line 337 of file AP_Camera.cpp.
Referenced by setup_feedback_callback().
bool AP_Camera::check_trigger_pin (void) private
Definition at line 324 of file AP_Camera.cpp.
Referenced by update_trigger().
void AP_Camera::configure (float shooting_mode, float shutter_speed, float aperture, float ISO, float exposure_type, float cmd_id, float engine_cutoff_time)
Definition at line 182 of file AP_Camera.cpp.
Referenced by AP_Camera(), GCS_MAVLINK::handle_command_camera(), and loop().
void AP_Camera::control (float session, float zoom_pos, float zoom_step, float focus_lock, float shooting_cmd, float cmd_id)
Definition at line 207 of file AP_Camera.cpp.
Referenced by AP_Camera(), control_msg(), GCS_MAVLINK::handle_command_camera(), and loop().
void AP_Camera::control_msg (const mavlink_message_t * msg)
decode deprecated MavLink message that controls camera.
Definition at line 174 of file AP_Camera.cpp.
Referenced by AP_Camera(), GCS_MAVLINK::handle_common_camera_message(), and loop().
void AP_Camera::feedback_pin_timer (void) private
Definition at line 300 of file AP_Camera.cpp.
Referenced by setup_feedback_callback().
void AP_Camera::log_picture () private
Definition at line 388 of file AP_Camera.cpp.
Referenced by trigger_pic().
void AP_Camera::relay_pic () private
basic relay activation
Definition at line 117 of file AP_Camera.cpp.
Referenced by trigger_pic().
void AP_Camera::send_feedback (mavlink_channel_t chan)
Definition at line 236 of file AP_Camera.cpp.
Referenced by AP_Camera().
void AP_Camera::servo_pic () private
Servo operated camera.
Definition at line 107 of file AP_Camera.cpp.
Referenced by trigger_pic().
void AP_Camera::set_trigger_distance (uint32_t distance_m) inline
Definition at line 58 of file AP_Camera.h.
Referenced by GCS_MAVLINK::handle_command_camera().
void AP_Camera::setup_feedback_callback (void) private
Definition at line 348 of file AP_Camera.cpp.
Referenced by trigger_pic().
void AP_Camera::take_picture ()
Definition at line 407 of file AP_Camera.cpp.
Referenced by set_trigger_distance(), and update().
void AP_Camera::trigger_pic () private
single entry point to take pictures set send_mavlink_msg to true to send DO_DIGICAM_CONTROL message to all components
Definition at line 131 of file AP_Camera.cpp.
Referenced by control(), and take_picture().
void AP_Camera::trigger_pic_cleanup () private
de-activate the trigger after some delay, but without using a delay() function should be called at 50hz
Definition at line 152 of file AP_Camera.cpp.
Referenced by update_trigger().
void AP_Camera::update (void)
Definition at line 259 of file AP_Camera.cpp.
Referenced by set_trigger_distance().
void AP_Camera::update_trigger ()
Definition at line 428 of file AP_Camera.cpp.
Referenced by set_trigger_distance().
bool AP_Camera::using_feedback_pin (void) const inline private
Definition at line 122 of file AP_Camera.h.
Referenced by log_picture().
Member Data Documentation
AP_Relay* AP_Camera::_apm_relay private
Definition at line 77 of file AP_Camera.h.
Referenced by AP_Camera(), relay_pic(), and trigger_pic_cleanup().
volatile bool AP_Camera::_camera_triggered static private
Definition at line 100 of file AP_Camera.h.
Referenced by capture_callback(), check_trigger_pin(), and feedback_pin_timer().
AP_Int8 AP_Camera::_feedback_pin private
Definition at line 96 of file AP_Camera.h.
Referenced by feedback_pin_timer(), and setup_feedback_callback().
AP_Int8 AP_Camera::_feedback_polarity private
Definition at line 97 of file AP_Camera.h.
Referenced by feedback_pin_timer(), and setup_feedback_callback().
uint16_t AP_Camera::_image_index private
Definition at line 93 of file AP_Camera.h.
Referenced by send_feedback(), and trigger_pic().
struct Location AP_Camera::_last_location private
Definition at line 92 of file AP_Camera.h.
Referenced by update().
uint32_t AP_Camera::_last_photo_time private
Definition at line 91 of file AP_Camera.h.
Referenced by update().
uint8_t AP_Camera::_last_pin_state private
Definition at line 102 of file AP_Camera.h.
Referenced by feedback_pin_timer().
AP_Int16 AP_Camera::_max_roll private
Definition at line 90 of file AP_Camera.h.
Referenced by update().
AP_Int16 AP_Camera::_min_interval private
Definition at line 89 of file AP_Camera.h.
Referenced by update().
AP_Int8 AP_Camera::_relay_on private
Definition at line 73 of file AP_Camera.h.
Referenced by relay_pic(), and trigger_pic_cleanup().
AP_Int16 AP_Camera::_servo_off_pwm private
Definition at line 75 of file AP_Camera.h.
Referenced by trigger_pic_cleanup().
AP_Int16 AP_Camera::_servo_on_pwm private
Definition at line 74 of file AP_Camera.h.
Referenced by servo_pic().
bool AP_Camera::_timer_installed private
Definition at line 101 of file AP_Camera.h.
Referenced by setup_feedback_callback().
AP_Float AP_Camera::_trigg_dist private
Definition at line 88 of file AP_Camera.h.
Referenced by set_trigger_distance(), and update().
uint8_t AP_Camera::_trigger_counter private
Definition at line 76 of file AP_Camera.h.
Referenced by relay_pic(), servo_pic(), and trigger_pic_cleanup().
AP_Int8 AP_Camera::_trigger_duration private
Definition at line 72 of file AP_Camera.h.
Referenced by relay_pic(), and servo_pic().
AP_Int8 AP_Camera::_trigger_type private
Definition at line 71 of file AP_Camera.h.
Referenced by trigger_pic(), and trigger_pic_cleanup().
const AP_AHRS& AP_Camera::ahrs private
Definition at line 109 of file AP_Camera.h.
Referenced by log_picture(), send_feedback(), update(), and update_trigger().
const struct Location& AP_Camera::current_loc private
Definition at line 107 of file AP_Camera.h.
Referenced by log_picture(), send_feedback(), update(), and update_trigger().
const AP_GPS& AP_Camera::gps private
Definition at line 108 of file AP_Camera.h.
Referenced by log_picture(), send_feedback(), update(), and update_trigger().
uint32_t AP_Camera::log_camera_bit private
Definition at line 106 of file AP_Camera.h.
Referenced by log_picture(), and update_trigger().
const AP_Param::GroupInfo AP_Camera::var_info static
Definition at line 68 of file AP_Camera.h.
Referenced by AP_Camera().
The documentation for this class was generated from the following files:
libraries/AP_Camera/AP_Camera.h
libraries/AP_Camera/AP_Camera.cpp
libraries/GCS_MAVLink/examples/routing/routing.cpp