APM:Libraries: AP_Motors Class Reference
AP_Motors Class Reference abstract
#include <AP_Motors_Class.h>
Classes
struct AP_Motors_flags
struct AP_Motors_limit
Public Types
enum motor_frame_class {
MOTOR_FRAME_UNDEFINED = 0, MOTOR_FRAME_QUAD = 1, MOTOR_FRAME_HEXA = 2, MOTOR_FRAME_OCTA = 3,
MOTOR_FRAME_OCTAQUAD = 4, MOTOR_FRAME_Y6 = 5, MOTOR_FRAME_HELI = 6, MOTOR_FRAME_TRI = 7,
MOTOR_FRAME_SINGLE = 8, MOTOR_FRAME_COAX = 9, MOTOR_FRAME_TAILSITTER = 10, MOTOR_FRAME_HELI_DUAL = 11,
MOTOR_FRAME_DODECAHEXA = 12
}
enum motor_frame_type {
MOTOR_FRAME_TYPE_PLUS = 0, MOTOR_FRAME_TYPE_X = 1, MOTOR_FRAME_TYPE_V = 2, MOTOR_FRAME_TYPE_H = 3,
MOTOR_FRAME_TYPE_VTAIL = 4, MOTOR_FRAME_TYPE_ATAIL = 5, MOTOR_FRAME_TYPE_Y6B = 10, MOTOR_FRAME_TYPE_Y6F = 11
}
enum spool_up_down_desired { DESIRED_SHUT_DOWN = 0, DESIRED_SPIN_WHEN_ARMED = 1, DESIRED_THROTTLE_UNLIMITED = 2 }
enum pwm_type { PWM_TYPE_NORMAL =0, PWM_TYPE_ONESHOT =1, PWM_TYPE_ONESHOT125 =2, PWM_TYPE_BRUSHED =3 }
Public Member Functions
AP_Motors (uint16_t loop_rate, uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
bool initialised_ok () const
bool armed () const
void armed (bool arm)
void set_interlock (bool set)
bool get_interlock () const
void set_roll (float roll_in)
void set_pitch (float pitch_in)
void set_yaw (float yaw_in)
void set_throttle (float throttle_in)
void set_throttle_avg_max (float throttle_avg_max)
void set_throttle_filter_cutoff (float filt_hz)
void set_forward (float forward_in)
void set_lateral (float lateral_in)
float get_roll () const
float get_pitch () const
float get_yaw () const
float get_throttle () const
float get_throttle_bidirectional () const
float get_forward () const
float get_lateral () const
virtual float get_throttle_hover () const =0
virtual void set_desired_spool_state (enum spool_up_down_desired spool)
enum spool_up_down_desired get_desired_spool_state (void) const
void set_voltage (float volts)
void set_voltage_resting_estimate (float volts)
void set_current (float current)
float get_batt_resistance () const
void set_resistance (float resistance)
void set_air_density_ratio (float ratio)
virtual void set_update_rate (uint16_t speed_hz)
virtual void init (motor_frame_class frame_class, motor_frame_type frame_type)=0
virtual void set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type)=0
virtual void enable ()=0
virtual void output ()=0
virtual void output_min ()=0
virtual void output_test (uint8_t motor_seq, int16_t pwm)=0
virtual uint16_t get_motor_mask ()=0
void set_radio_passthrough (float roll_input, float pitch_input, float throttle_input, float yaw_input)
void set_loop_rate (uint16_t loop_rate)
pwm_type get_pwm_type (void) const
Public Attributes
struct AP_Motors::AP_Motors_limit limit
Protected Member Functions
virtual void output_armed_stabilizing ()=0
virtual void rc_write (uint8_t chan, uint16_t pwm)
virtual void rc_set_freq (uint32_t mask, uint16_t freq_hz)
virtual void rc_enable_ch (uint8_t chan)
virtual uint32_t rc_map_mask (uint32_t mask) const
void add_motor_num (int8_t motor_num)
virtual void update_throttle_filter ()=0
virtual void save_params_on_disarm ()
int16_t calc_pwm_output_1to1 (float input, const SRV_Channel *servo)
int16_t calc_pwm_output_0to1 (float input, const SRV_Channel *servo)
Protected Attributes
struct AP_Motors::AP_Motors_flags _flags
uint16_t _loop_rate
uint16_t _speed_hz
float _roll_in
float _pitch_in
float _yaw_in
float _throttle_in
float _forward_in
float _lateral_in
float _throttle_avg_max
LowPassFilterFloat _throttle_filter
spool_up_down_desired _spool_desired
float _batt_voltage
float _batt_voltage_resting_estimate
float _batt_current
float _batt_resistance
float _air_density_ratio
uint8_t _motor_map [AP_MOTORS_MAX_NUM_MOTORS]
uint16_t _motor_map_mask
uint16_t _motor_fast_mask
float _roll_radio_passthrough = 0.0f
float _pitch_radio_passthrough = 0.0f
float _throttle_radio_passthrough = 0.0f
float _yaw_radio_passthrough = 0.0f
AP_Int8 _pwm_type
Detailed Description
Definition at line 29 of file AP_Motors_Class.h.
Member Enumeration Documentation
enum AP_Motors::motor_frame_class
Enumerator
MOTOR_FRAME_UNDEFINED
MOTOR_FRAME_QUAD
MOTOR_FRAME_HEXA
MOTOR_FRAME_OCTA
MOTOR_FRAME_OCTAQUAD
MOTOR_FRAME_Y6
MOTOR_FRAME_HELI
MOTOR_FRAME_TRI
MOTOR_FRAME_SINGLE
MOTOR_FRAME_COAX
MOTOR_FRAME_TAILSITTER
MOTOR_FRAME_HELI_DUAL
MOTOR_FRAME_DODECAHEXA
Definition at line 32 of file AP_Motors_Class.h.
enum AP_Motors::motor_frame_type
Enumerator
MOTOR_FRAME_TYPE_PLUS
MOTOR_FRAME_TYPE_X
MOTOR_FRAME_TYPE_V
MOTOR_FRAME_TYPE_H
MOTOR_FRAME_TYPE_VTAIL
MOTOR_FRAME_TYPE_ATAIL
MOTOR_FRAME_TYPE_Y6B
MOTOR_FRAME_TYPE_Y6F
Definition at line 47 of file AP_Motors_Class.h.
enum AP_Motors::pwm_type
Enumerator
PWM_TYPE_NORMAL
PWM_TYPE_ONESHOT
PWM_TYPE_ONESHOT125
PWM_TYPE_BRUSHED
Definition at line 167 of file AP_Motors_Class.h.
enum AP_Motors::spool_up_down_desired
Enumerator
DESIRED_SHUT_DOWN
DESIRED_SPIN_WHEN_ARMED
DESIRED_THROTTLE_UNLIMITED
Definition at line 95 of file AP_Motors_Class.h.
Constructor & Destructor Documentation
AP_Motors::AP_Motors (uint16_t loop_rate, uint16_t speed_hz = AP_MOTORS_SPEED_DEFAULT)
Definition at line 29 of file AP_Motors_Class.cpp.
Member Function Documentation
void AP_Motors::add_motor_num (int8_t motor_num) protected
Definition at line 196 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsMatrix::add_motor_raw(), get_pwm_type(), AP_MotorsTri::init(), and AP_MotorsSingle::init().
bool AP_Motors::armed () const inline
Definition at line 65 of file AP_Motors_Class.h.
Referenced by motor_order_test(), AP_MotorsMatrix::output_test(), AP_MotorsTri::output_test(), AP_MotorsSingle::output_test(), AP_MotorsCoax::output_test(), AP_MotorsHeli_Dual::output_test(), AP_MotorsHeli_Single::output_test(), AP_MotorsMatrix::output_to_motors(), AP_MotorsMatrix::set_frame_class_and_type(), AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration(), stability_test(), and AP_MotorsMulticopter::update_throttle_filter().
void AP_Motors::armed (bool arm)
Definition at line 61 of file AP_Motors_Class.cpp.
int16_t AP_Motors::calc_pwm_output_0to1 (float input, const SRV_Channel * servo) protected
Definition at line 178 of file AP_Motors_Class.cpp.
Referenced by save_params_on_disarm(), and AP_MotorsHeli_Single::write_aux().
int16_t AP_Motors::calc_pwm_output_1to1 (float input, const SRV_Channel * servo) protected
Definition at line 158 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsHeli_Dual::move_actuators(), AP_MotorsHeli_Single::move_actuators(), AP_MotorsHeli_Single::move_yaw(), AP_MotorsSingle::output_to_motors(), AP_MotorsCoax::output_to_motors(), and save_params_on_disarm().
virtual void AP_Motors::enable () pure virtual
Implemented in AP_MotorsHeli, AP_MotorsHeli_Single, AP_MotorsHeli_Dual, AP_MotorsCoax, AP_MotorsSingle, AP_MotorsTri, AP_MotorsMatrix, and AP_MotorsTailsitter.
Referenced by set_update_rate().
float AP_Motors::get_batt_resistance () const inline
Definition at line 116 of file AP_Motors_Class.h.
enum spool_up_down_desired AP_Motors::get_desired_spool_state (void) const inline
Definition at line 103 of file AP_Motors_Class.h.
float AP_Motors::get_forward () const inline
Definition at line 90 of file AP_Motors_Class.h.
bool AP_Motors::get_interlock () const inline
Definition at line 72 of file AP_Motors_Class.h.
float AP_Motors::get_lateral () const inline
Definition at line 91 of file AP_Motors_Class.h.
virtual uint16_t AP_Motors::get_motor_mask () pure virtual
Implemented in AP_MotorsHeli, AP_MotorsHeli_Single, AP_MotorsHeli_Dual, AP_MotorsCoax, AP_MotorsSingle, AP_MotorsTri, AP_MotorsMatrix, and AP_MotorsTailsitter.
Referenced by set_update_rate().
float AP_Motors::get_pitch () const inline
Definition at line 86 of file AP_Motors_Class.h.
Referenced by DataFlash_Class::Log_Write_Rate().
pwm_type AP_Motors::get_pwm_type (void) const inline
Definition at line 168 of file AP_Motors_Class.h.
float AP_Motors::get_roll () const inline
Definition at line 85 of file AP_Motors_Class.h.
Referenced by DataFlash_Class::Log_Write_Rate().
float AP_Motors::get_throttle () const inline
Definition at line 88 of file AP_Motors_Class.h.
Referenced by AC_PosControl::init_takeoff(), DataFlash_Class::Log_Write_Rate(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsHeli::output_armed_stabilizing(), AP_MotorsHeli::output_armed_zero_throttle(), AP_MotorsMulticopter::output_boost_throttle(), AP_MotorsHeli::output_disarmed(), AP_MotorsMulticopter::output_logic(), and AP_MotorsMulticopter::update_throttle_hover().
float AP_Motors::get_throttle_bidirectional () const inline
Definition at line 89 of file AP_Motors_Class.h.
Referenced by AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), and AP_Motors6DOF::output_armed_stabilizing_vectored_6dof().
virtual float AP_Motors::get_throttle_hover () const pure virtual
Implemented in AP_MotorsHeli, and AP_MotorsMulticopter.
Referenced by AC_PosControl::accel_to_throttle(), get_lateral(), AC_AttitudeControl_Sub::get_throttle_avg_max(), AC_AttitudeControl_Multi::get_throttle_avg_max(), AC_PosControl::init_takeoff(), AC_AttitudeControl::max_rate_step_bf_pitch(), AC_AttitudeControl::max_rate_step_bf_roll(), AC_AttitudeControl::max_rate_step_bf_yaw(), and AC_PosControl::relax_alt_hold_controllers().
float AP_Motors::get_yaw () const inline
Definition at line 87 of file AP_Motors_Class.h.
Referenced by DataFlash_Class::Log_Write_Rate().
virtual void AP_Motors::init (motor_frame_class frame_class, motor_frame_type frame_type) pure virtual
Implemented in AP_MotorsHeli, AP_MotorsCoax, AP_MotorsSingle, AP_MotorsTri, and AP_MotorsTailsitter.
Referenced by set_update_rate().
bool AP_Motors::initialised_ok () const inline
Definition at line 62 of file AP_Motors_Class.h.
virtual void AP_Motors::output () pure virtual
Implemented in AP_MotorsHeli, and AP_MotorsMulticopter.
Referenced by set_update_rate().
virtual void AP_Motors::output_armed_stabilizing () protected pure virtual
Implemented in AP_MotorsHeli, AP_MotorsCoax, AP_MotorsSingle, AP_MotorsTri, AP_Motors6DOF, AP_MotorsMatrix, and AP_MotorsTailsitter.
Referenced by get_pwm_type(), and AP_MotorsMulticopter::output().
virtual void AP_Motors::output_min () pure virtual
Implemented in AP_MotorsHeli, AP_MotorsMulticopter, and AP_Motors6DOF.
Referenced by set_update_rate().
virtual void AP_Motors::output_test (uint8_t motor_seq, int16_t pwm) pure virtual
Implemented in AP_MotorsHeli, AP_MotorsHeli_Single, AP_MotorsHeli_Dual, AP_MotorsCoax, AP_MotorsSingle, AP_MotorsTri, AP_MotorsMatrix, and AP_MotorsTailsitter.
Referenced by set_update_rate().
void AP_Motors::rc_enable_ch (uint8_t chan) protected virtual
Definition at line 128 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsMatrix::enable(), AP_MotorsTri::enable(), AP_MotorsCoax::enable(), AP_MotorsSingle::enable(), AP_MotorsHeli_Dual::enable(), AP_MotorsHeli_Single::enable(), and get_pwm_type().
uint32_t AP_Motors::rc_map_mask (uint32_t mask) const protected virtual
Definition at line 140 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsMatrix::get_motor_mask(), AP_MotorsTri::get_motor_mask(), AP_MotorsCoax::get_motor_mask(), AP_MotorsSingle::get_motor_mask(), AP_MotorsHeli_Single::get_motor_mask(), get_pwm_type(), and rc_set_freq().
void AP_Motors::rc_set_freq (uint32_t mask, uint16_t freq_hz) protected virtual
Definition at line 110 of file AP_Motors_Class.cpp.
Referenced by get_pwm_type(), AP_MotorsMatrix::set_update_rate(), AP_MotorsTri::set_update_rate(), AP_MotorsCoax::set_update_rate(), AP_MotorsSingle::set_update_rate(), AP_MotorsHeli_Dual::set_update_rate(), and AP_MotorsHeli_Single::set_update_rate().
void AP_Motors::rc_write (uint8_t chan, uint16_t pwm) protected virtual
Definition at line 84 of file AP_Motors_Class.cpp.
Referenced by get_pwm_type(), AP_MotorsHeli_Dual::move_actuators(), AP_MotorsHeli_Single::move_actuators(), AP_MotorsHeli_Single::move_yaw(), AP_Motors6DOF::output_min(), AP_MotorsTri::output_motor_mask(), AP_MotorsMulticopter::output_motor_mask(), AP_MotorsMatrix::output_test(), AP_MotorsTri::output_test(), AP_MotorsSingle::output_test(), AP_MotorsCoax::output_test(), AP_MotorsHeli_Dual::output_test(), AP_MotorsHeli_Single::output_test(), AP_MotorsMatrix::output_to_motors(), AP_Motors6DOF::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsCoax::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration(), and AP_MotorsHeli_Single::write_aux().
virtual void AP_Motors::save_params_on_disarm () inline protected virtual
Reimplemented in AP_MotorsMulticopter.
Definition at line 185 of file AP_Motors_Class.h.
Referenced by armed().
void AP_Motors::set_air_density_ratio (float ratio) inline
Definition at line 120 of file AP_Motors_Class.h.
void AP_Motors::set_current (float current) inline
Definition at line 113 of file AP_Motors_Class.h.
virtual void AP_Motors::set_desired_spool_state (enum spool_up_down_desired spool) inline virtual
Definition at line 101 of file AP_Motors_Class.h.
Referenced by AP_MotorsMulticopter::output_min(), and stability_test().
void AP_Motors::set_forward (float forward_in) inline
Definition at line 81 of file AP_Motors_Class.h.
virtual void AP_Motors::set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type) pure virtual
Implemented in AP_MotorsHeli, AP_MotorsCoax, AP_MotorsSingle, AP_MotorsTri, and AP_MotorsTailsitter.
Referenced by set_update_rate().
void AP_Motors::set_interlock (bool set) inline
Definition at line 69 of file AP_Motors_Class.h.
Referenced by stability_test().
void AP_Motors::set_lateral (float lateral_in) inline
Definition at line 82 of file AP_Motors_Class.h.
void AP_Motors::set_loop_rate (uint16_t loop_rate) inline
Definition at line 165 of file AP_Motors_Class.h.
void AP_Motors::set_pitch (float pitch_in) inline
Definition at line 76 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), and stability_test().
void AP_Motors::set_radio_passthrough (float roll_input, float pitch_input, float throttle_input, float yaw_input)
Definition at line 73 of file AP_Motors_Class.cpp.
Referenced by set_update_rate().
void AP_Motors::set_resistance (float resistance) inline
Definition at line 117 of file AP_Motors_Class.h.
void AP_Motors::set_roll (float roll_in) inline
Definition at line 75 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), and stability_test().
void AP_Motors::set_throttle (float throttle_in) inline
Definition at line 78 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Sub::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), AC_AttitudeControl_Heli::set_throttle_out(), AC_AttitudeControl::set_throttle_out_unstabilized(), and stability_test().
void AP_Motors::set_throttle_avg_max (float throttle_avg_max) inline
Definition at line 79 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Sub::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), and setup().
void AP_Motors::set_throttle_filter_cutoff (float filt_hz) inline
Definition at line 80 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Sub::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), AC_AttitudeControl_Heli::set_throttle_out(), and AC_AttitudeControl::set_throttle_out_unstabilized().
virtual void AP_Motors::set_update_rate (uint16_t speed_hz) inline virtual
Reimplemented in AP_MotorsHeli, AP_MotorsHeli_Single, AP_MotorsHeli_Dual, AP_MotorsCoax, AP_MotorsSingle, AP_MotorsTri, AP_MotorsMatrix, and AP_MotorsTailsitter.
Definition at line 135 of file AP_Motors_Class.h.
void AP_Motors::set_voltage (float volts) inline
Definition at line 109 of file AP_Motors_Class.h.
void AP_Motors::set_voltage_resting_estimate (float volts) inline
Definition at line 110 of file AP_Motors_Class.h.
void AP_Motors::set_yaw (float yaw_in) inline
Definition at line 77 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), and stability_test().
virtual void AP_Motors::update_throttle_filter () protected pure virtual
Implemented in AP_MotorsHeli, and AP_MotorsMulticopter.
Referenced by get_pwm_type().
Member Data Documentation
float AP_Motors::_air_density_ratio protected
Definition at line 218 of file AP_Motors_Class.h.
Referenced by AP_MotorsMulticopter::get_compensation_gain(), and set_air_density_ratio().
float AP_Motors::_batt_current protected
Definition at line 216 of file AP_Motors_Class.h.
Referenced by AP_MotorsMulticopter::get_current_limit_max_throttle(), and set_current().
float AP_Motors::_batt_resistance protected
Definition at line 217 of file AP_Motors_Class.h.
Referenced by get_batt_resistance(), AP_MotorsMulticopter::get_current_limit_max_throttle(), and set_resistance().
float AP_Motors::_batt_voltage protected
Definition at line 214 of file AP_Motors_Class.h.
Referenced by AP_MotorsMulticopter::get_current_limit_max_throttle(), set_voltage(), and AP_MotorsMulticopter::update_lift_max_from_batt_voltage().
float AP_Motors::_batt_voltage_resting_estimate protected
Definition at line 215 of file AP_Motors_Class.h.
Referenced by set_voltage_resting_estimate(), and AP_MotorsMulticopter::update_lift_max_from_batt_voltage().
struct AP_Motors::AP_Motors_flags AP_Motors::_flags protected
Referenced by AP_Motors(), armed(), AP_MotorsMulticopter::get_current_limit_max_throttle(), get_interlock(), AP_MotorsTailsitter::init(), AP_MotorsTri::init(), AP_MotorsSingle::init(), AP_MotorsCoax::init(), AP_MotorsHeli::init(), AP_MotorsHeli_Dual::init_outputs(), AP_MotorsHeli_Single::init_outputs(), initialised_ok(), AP_MotorsHeli::output(), AP_MotorsMulticopter::output_logic(), AP_MotorsTailsitter::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTri::set_frame_class_and_type(), AP_MotorsCoax::set_frame_class_and_type(), AP_MotorsHeli::set_frame_class_and_type(), set_interlock(), and AP_MotorsMatrix::setup_motors().
float AP_Motors::_forward_in protected
Definition at line 207 of file AP_Motors_Class.h.
Referenced by get_forward(), AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and set_forward().
float AP_Motors::_lateral_in protected
Definition at line 208 of file AP_Motors_Class.h.
Referenced by get_lateral(), AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and set_lateral().
uint16_t AP_Motors::_loop_rate protected
Definition at line 201 of file AP_Motors_Class.h.
Referenced by AP_MotorsMulticopter::get_current_limit_max_throttle(), AP_MotorsMulticopter::output_logic(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), set_loop_rate(), AP_MotorsMulticopter::update_lift_max_from_batt_voltage(), AP_MotorsMulticopter::update_throttle_filter(), and AP_MotorsHeli::update_throttle_filter().
uint16_t AP_Motors::_motor_fast_mask protected
Definition at line 223 of file AP_Motors_Class.h.
Referenced by rc_set_freq(), and rc_write().
uint8_t AP_Motors::_motor_map[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 221 of file AP_Motors_Class.h.
Referenced by add_motor_num(), rc_enable_ch(), rc_map_mask(), and rc_write().
uint16_t AP_Motors::_motor_map_mask protected
Definition at line 222 of file AP_Motors_Class.h.
Referenced by add_motor_num(), rc_enable_ch(), rc_map_mask(), and rc_write().
float AP_Motors::_pitch_in protected
Definition at line 204 of file AP_Motors_Class.h.
Referenced by get_pitch(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsHeli::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsHeli::output_armed_zero_throttle(), AP_MotorsHeli::output_disarmed(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), and set_pitch().
float AP_Motors::_pitch_radio_passthrough = 0.0f protected
Definition at line 227 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::output_disarmed(), AP_MotorsSingle::output_to_motors(), AP_MotorsCoax::output_to_motors(), and set_radio_passthrough().
AP_Int8 AP_Motors::_pwm_type protected
Definition at line 231 of file AP_Motors_Class.h.
Referenced by get_pwm_type(), rc_set_freq(), and rc_write().
float AP_Motors::_roll_in protected
Definition at line 203 of file AP_Motors_Class.h.
Referenced by get_roll(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsHeli::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsHeli::output_armed_zero_throttle(), AP_MotorsHeli::output_disarmed(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), and set_roll().
float AP_Motors::_roll_radio_passthrough = 0.0f protected
Definition at line 226 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::output_disarmed(), AP_MotorsSingle::output_to_motors(), AP_MotorsCoax::output_to_motors(), and set_radio_passthrough().
uint16_t AP_Motors::_speed_hz protected
Definition at line 202 of file AP_Motors_Class.h.
Referenced by AP_MotorsMatrix::init(), AP_MotorsTri::init(), AP_MotorsSingle::init(), AP_MotorsHeli::init(), AP_MotorsMatrix::set_frame_class_and_type(), AP_MotorsMatrix::set_update_rate(), AP_MotorsTri::set_update_rate(), AP_MotorsSingle::set_update_rate(), AP_MotorsCoax::set_update_rate(), AP_MotorsHeli_Dual::set_update_rate(), AP_MotorsHeli_Single::set_update_rate(), and set_update_rate().
spool_up_down_desired AP_Motors::_spool_desired protected
Definition at line 211 of file AP_Motors_Class.h.
Referenced by get_desired_spool_state(), AP_MotorsMulticopter::output_logic(), and set_desired_spool_state().
float AP_Motors::_throttle_avg_max protected
Definition at line 209 of file AP_Motors_Class.h.
Referenced by AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), and set_throttle_avg_max().
LowPassFilterFloat AP_Motors::_throttle_filter protected
Definition at line 210 of file AP_Motors_Class.h.
Referenced by AP_Motors(), get_throttle(), get_throttle_bidirectional(), AP_MotorsHeli::output_disarmed(), set_throttle_filter_cutoff(), AP_MotorsMulticopter::update_throttle_filter(), and AP_MotorsHeli::update_throttle_filter().
float AP_Motors::_throttle_in protected
Definition at line 206 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), set_throttle(), AP_MotorsMulticopter::update_throttle_filter(), and AP_MotorsHeli::update_throttle_filter().
float AP_Motors::_throttle_radio_passthrough = 0.0f protected
Definition at line 228 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::init(), AP_MotorsHeli::output_disarmed(), and set_radio_passthrough().
float AP_Motors::_yaw_in protected
Definition at line 205 of file AP_Motors_Class.h.
Referenced by get_yaw(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsHeli::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsHeli::output_armed_zero_throttle(), AP_MotorsHeli::output_disarmed(), AP_MotorsHeli_Single::servo_test(), and set_yaw().
float AP_Motors::_yaw_radio_passthrough = 0.0f protected
Definition at line 229 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::output_disarmed(), AP_MotorsSingle::output_to_motors(), and set_radio_passthrough().
struct AP_Motors::AP_Motors_limit AP_Motors::limit
Referenced by AC_PosControl::accel_to_throttle(), AP_Motors(), AP_MotorsHeli_Dual::move_actuators(), AP_MotorsHeli_Single::move_actuators(), AP_MotorsHeli_Single::move_yaw(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsMulticopter::output_logic(), AP_Motors6DOF::output_min(), AP_MotorsHeli::output_min(), AP_MotorsTailsitter::output_to_motors(), AC_AttitudeControl::rate_target_to_motor_pitch(), AC_AttitudeControl::rate_target_to_motor_roll(), AC_AttitudeControl::rate_target_to_motor_yaw(), AC_PosControl::rate_to_accel_xy(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), AC_PosControl::set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), AC_PosControl::set_alt_target_from_climb_rate_ff(), AC_PosControl::set_alt_target_with_slew(), and stability_test().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_Motors_Class.h
libraries/AP_Motors/AP_Motors_Class.cpp