APM:Libraries: NavEKF2 Class Reference
NavEKF2 Class Reference
#include <AP_NavEKF2.h>
Public Member Functions
NavEKF2 (const AP_AHRS *ahrs, AP_Baro &baro, const RangeFinder &rng)
uint8_t activeCores (void) const
bool InitialiseFilter (void)
void UpdateFilter (void)
void check_log_write (void)
bool healthy (void) const
int8_t getPrimaryCoreIndex (void) const
int8_t getPrimaryCoreIMUIndex (void) const
bool getPosNE (int8_t instance, Vector2f &posNE)
bool getPosD (int8_t instance, float &posD)
void getVelNED (int8_t instance, Vector3f &vel)
float getPosDownDerivative (int8_t instance)
void getAccelNED (Vector3f &accelNED) const
void getGyroBias (int8_t instance, Vector3f &gyroBias)
void getGyroScaleErrorPercentage (int8_t instance, Vector3f &gyroScale)
void getTiltError (int8_t instance, float &ang)
void resetGyroBias (void)
bool resetHeightDatum (void)
uint8_t setInhibitGPS (void)
void getEkfControlLimits (float &ekfGndSpdLimit, float &ekfNavVelGainScaler) const
void getAccelZBias (int8_t instance, float &zbias)
void getWind (int8_t instance, Vector3f &wind)
void getMagNED (int8_t instance, Vector3f &magNED)
void getMagXYZ (int8_t instance, Vector3f &magXYZ)
uint8_t getActiveMag (int8_t instance)
bool getMagOffsets (uint8_t mag_idx, Vector3f &magOffsets) const
bool getLLH (struct Location &loc) const
bool getOriginLLH (int8_t instance, struct Location &loc) const
bool setOriginLLH (const Location &loc)
bool getHAGL (float &HAGL) const
void getEulerAngles (int8_t instance, Vector3f &eulers)
void getRotationBodyToNED (Matrix3f &mat) const
void getQuaternion (int8_t instance, Quaternion &quat) const
void getInnovations (int8_t index, Vector3f &velInnov, Vector3f &posInnov, Vector3f &magInnov, float &tasInnov, float &yawInnov)
void getOutputTrackingError (int8_t instance, Vector3f &error) const
void getVariances (int8_t instance, float &velVar, float &posVar, float &hgtVar, Vector3f &magVar, float &tasVar, Vector2f &offset)
bool use_compass (void) const
void writeOptFlowMeas (uint8_t &rawFlowQuality, Vector2f &rawFlowRates, Vector2f &rawGyroRates, uint32_t &msecFlowMeas, const Vector3f &posOffset)
void getFlowDebug (int8_t instance, float &varFlow, float &gndOffset, float &flowInnovX, float &flowInnovY, float &auxInnov, float &HAGL, float &rngInnov, float &range, float &gndOffsetErr)
bool getRangeBeaconDebug (int8_t instance, uint8_t &ID, float &rng, float &innov, float &innovVar, float &testRatio, Vector3f &beaconPosNED, float &offsetHigh, float &offsetLow)
void setTakeoffExpected (bool val)
void setTouchdownExpected (bool val)
void setTerrainHgtStable (bool val)
void getFilterFaults (int8_t instance, uint16_t &faults)
void getFilterTimeouts (int8_t instance, uint8_t &timeouts)
void getFilterGpsStatus (int8_t instance, nav_gps_status &faults)
void getFilterStatus (int8_t instance, nav_filter_status &status)
void send_status_report (mavlink_channel_t chan)
bool getHeightControlLimit (float &height) const
uint32_t getLastYawResetAngle (float &yawAngDelta)
uint32_t getLastPosNorthEastReset (Vector2f &posDelta)
uint32_t getLastVelNorthEastReset (Vector2f &vel) const
uint32_t getLastPosDownReset (float &posDelta)
const char * prearm_failure_reason (void) const
void set_baro_alt_noise (float noise)
void set_enable (bool enable)
bool have_ekf_logging (void) const
void getTimingStatistics (int8_t instance, struct ekf_timing &timing)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void updateLaneSwitchYawResetData (uint8_t new_primary, uint8_t old_primary)
void updateLaneSwitchPosResetData (uint8_t new_primary, uint8_t old_primary)
void updateLaneSwitchPosDownResetData (uint8_t new_primary, uint8_t old_primary)
Private Attributes
uint8_t num_cores
uint8_t primary
NavEKF2_core * core = nullptr
const AP_AHRS * _ahrs
AP_Baro & _baro
const RangeFinder & _rng
uint32_t _frameTimeUsec
uint8_t _framesPerPrediction
AP_Int8 _enable
AP_Float _gpsHorizVelNoise
AP_Float _gpsVertVelNoise
AP_Float _gpsHorizPosNoise
AP_Float _baroAltNoise
AP_Float _magNoise
AP_Float _easNoise
AP_Float _windVelProcessNoise
AP_Float _wndVarHgtRateScale
AP_Float _magEarthProcessNoise
AP_Float _magBodyProcessNoise
AP_Float _gyrNoise
AP_Float _accNoise
AP_Float _gyroBiasProcessNoise
AP_Float _accelBiasProcessNoise
AP_Int16 _gpsDelay_ms
AP_Int16 _hgtDelay_ms
AP_Int8 _fusionModeGPS
AP_Int16 _gpsVelInnovGate
AP_Int16 _gpsPosInnovGate
AP_Int16 _hgtInnovGate
AP_Int16 _magInnovGate
AP_Int16 _tasInnovGate
AP_Int8 _magCal
AP_Int8 _gpsGlitchRadiusMax
AP_Float _flowNoise
AP_Int16 _flowInnovGate
AP_Int8 _flowDelay_ms
AP_Int16 _rngInnovGate
AP_Float _maxFlowRate
AP_Int8 _altSource
AP_Float _gyroScaleProcessNoise
AP_Float _rngNoise
AP_Int8 _gpsCheck
AP_Int8 _imuMask
AP_Int16 _gpsCheckScaler
AP_Float _noaidHorizNoise
AP_Int8 _logging_mask
AP_Float _yawNoise
AP_Int16 _yawInnovGate
AP_Int8 _tauVelPosOutput
AP_Int8 _useRngSwHgt
AP_Float _terrGradMax
AP_Float _rngBcnNoise
AP_Int16 _rngBcnInnovGate
AP_Int8 _rngBcnDelay_ms
AP_Float _useRngSwSpd
AP_Int8 _magMask
AP_Int8 _originHgtMode
const float gpsNEVelVarAccScale
const float gpsDVelVarAccScale
const float gpsPosVarAccScale
const uint16_t magDelay_ms
const uint16_t tasDelay_ms
const uint16_t tiltDriftTimeMax_ms
const uint16_t posRetryTimeUseVel_ms
const uint16_t posRetryTimeNoVel_ms
const uint16_t hgtRetryTimeMode0_ms
const uint16_t hgtRetryTimeMode12_ms
const uint16_t tasRetryTime_ms
const uint32_t magFailTimeLimit_ms
const float magVarRateScale
const float gyroBiasNoiseScaler
const uint16_t hgtAvg_ms
const uint16_t betaAvg_ms
const float covTimeStepMax
const float covDelAngMax
const float DCM33FlowMin
const float fScaleFactorPnoise
const uint8_t flowTimeDeltaAvg_ms
const uint32_t flowIntervalMax_ms
const uint16_t gndEffectTimeout_ms
const float gndEffectBaroScaler
const uint8_t gndGradientSigma
const uint8_t fusionTimeStep_ms
struct {
bool enabled:1
bool log_compass:1
bool log_gps:1
bool log_baro:1
bool log_imu:1
} logging
uint64_t imuSampleTime_us
struct {
uint32_t last_function_call
bool core_changed
uint32_t last_primary_change
float core_delta
} yaw_reset_data
struct {
uint32_t last_function_call
bool core_changed
uint32_t last_primary_change
Vector2f core_delta
} pos_reset_data
struct {
uint32_t last_function_call
bool core_changed
uint32_t last_primary_change
float core_delta
} pos_down_reset_data
bool runCoreSelection
Friends
class NavEKF2_core
Detailed Description
Definition at line 37 of file AP_NavEKF2.h.
Constructor & Destructor Documentation
NavEKF2::NavEKF2 (const AP_AHRS * ahrs, AP_Baro & baro, const RangeFinder & rng)
Definition at line 556 of file AP_NavEKF2.cpp.
Member Function Documentation
uint8_t NavEKF2::activeCores (void) const inline
Definition at line 46 of file AP_NavEKF2.h.
Referenced by DataFlash_Class::Log_Write_POS(), and GCS_MAVLINK::send_ahrs2().
void NavEKF2::check_log_write (void)
Definition at line 594 of file AP_NavEKF2.cpp.
Referenced by activeCores(), InitialiseFilter(), and UpdateFilter().
void NavEKF2::getAccelNED (Vector3f & accelNED) const
Definition at line 844 of file AP_NavEKF2.cpp.
Referenced by activeCores().
void NavEKF2::getAccelZBias (int8_t instance, float & zbias)
Definition at line 932 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), DataFlash_Class::Log_Write_POS(), and AP_AHRS_NavEKF::update_EKF2().
uint8_t NavEKF2::getActiveMag (int8_t instance)
Definition at line 968 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getEkfControlLimits (float & ekfGndSpdLimit, float & ekfNavVelGainScaler) const
Definition at line 924 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::getEkfControlLimits().
void NavEKF2::getEulerAngles (int8_t instance, Vector3f & eulers)
Definition at line 1045 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_secondary_attitude(), DataFlash_Class::Log_Write_POS(), GCS_MAVLINK::send_ahrs2(), and AP_AHRS_NavEKF::update_EKF2().
void NavEKF2::getFilterFaults (int8_t instance, uint16_t & faults)
Definition at line 1190 of file AP_NavEKF2.cpp.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), activeCores(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getFilterGpsStatus (int8_t instance, nav_gps_status & faults)
Definition at line 1237 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getFilterStatus (int8_t instance, nav_filter_status & status)
Definition at line 1224 of file AP_NavEKF2.cpp.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), activeCores(), AP_AHRS_NavEKF::get_filter_status(), DataFlash_Class::Log_Write_POS(), and AP_AHRS_NavEKF::update_EKF2().
void NavEKF2::getFilterTimeouts (int8_t instance, uint8_t & timeouts)
Definition at line 1211 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getFlowDebug (int8_t instance, float & varFlow, float & gndOffset, float & flowInnovX, float & flowInnovY, float & auxInnov, float & HAGL, float & rngInnov, float & range, float & gndOffsetErr)
Definition at line 1124 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getGyroBias (int8_t instance, Vector3f & gyroBias)
Definition at line 852 of file AP_NavEKF2.cpp.
Referenced by activeCores(), DataFlash_Class::Log_Write_POS(), and AP_AHRS_NavEKF::update_EKF2().
void NavEKF2::getGyroScaleErrorPercentage (int8_t instance, Vector3f & gyroScale)
Definition at line 861 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
bool NavEKF2::getHAGL (float & HAGL) const
Definition at line 1036 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::get_hagl().
bool NavEKF2::getHeightControlLimit (float & height) const
Definition at line 1258 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::get_hgt_ctrl_limit().
void NavEKF2::getInnovations (int8_t index, Vector3f & velInnov, Vector3f & posInnov, Vector3f & magInnov, float & tasInnov, float & yawInnov)
Definition at line 1071 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
uint32_t NavEKF2::getLastPosDownReset (float & posDelta)
Definition at line 1364 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::getLastPosDownReset(), and updateLaneSwitchPosDownResetData().
uint32_t NavEKF2::getLastPosNorthEastReset (Vector2f & posDelta)
Definition at line 1307 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::getLastPosNorthEastReset(), and updateLaneSwitchPosResetData().
uint32_t NavEKF2::getLastVelNorthEastReset (Vector2f & vel) const
Definition at line 1344 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::getLastVelNorthEastReset().
uint32_t NavEKF2::getLastYawResetAngle (float & yawAngDelta)
Definition at line 1269 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::getLastYawResetAngle(), and updateLaneSwitchYawResetData().
bool NavEKF2::getLLH (struct Location & loc) const
Definition at line 1001 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_location(), AP_AHRS_NavEKF::get_position(), AP_AHRS_NavEKF::get_secondary_position(), and GCS_MAVLINK::send_ahrs2().
void NavEKF2::getMagNED (int8_t instance, Vector3f & magNED)
Definition at line 950 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_mag_field_NED(), and DataFlash_Class::Log_Write_POS().
bool NavEKF2::getMagOffsets (uint8_t mag_idx, Vector3f & magOffsets) const
Definition at line 980 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::getMagOffsets().
void NavEKF2::getMagXYZ (int8_t instance, Vector3f & magXYZ)
Definition at line 959 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_mag_field_correction(), and DataFlash_Class::Log_Write_POS().
bool NavEKF2::getOriginLLH (int8_t instance, struct Location & loc) const
Definition at line 1013 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_origin(), AP_AHRS_NavEKF::get_position(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getOutputTrackingError (int8_t instance, Vector3f & error) const
Definition at line 1080 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
bool NavEKF2::getPosD (int8_t instance, float & posD)
Definition at line 814 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_position(), AP_AHRS_NavEKF::get_relative_position_D_origin(), AP_AHRS_NavEKF::get_relative_position_NED_origin(), and DataFlash_Class::Log_Write_POS().
float NavEKF2::getPosDownDerivative (int8_t instance)
Definition at line 833 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_vert_pos_rate(), and DataFlash_Class::Log_Write_POS().
bool NavEKF2::getPosNE (int8_t instance, Vector2f & posNE)
Definition at line 802 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_relative_position_NE_origin(), AP_AHRS_NavEKF::get_relative_position_NED_origin(), and DataFlash_Class::Log_Write_POS().
int8_t NavEKF2::getPrimaryCoreIMUIndex (void) const
Definition at line 791 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_primary_IMU_index(), AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), and AP_AHRS_NavEKF::update_EKF2().
int8_t NavEKF2::getPrimaryCoreIndex (void) const
Definition at line 781 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getQuaternion (int8_t instance, Quaternion & quat) const
Definition at line 1062 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_secondary_quaternion(), and DataFlash_Class::Log_Write_POS().
bool NavEKF2::getRangeBeaconDebug (int8_t instance, uint8_t & ID, float & rng, float & innov, float & innovVar, float & testRatio, Vector3f & beaconPosNED, float & offsetHigh, float & offsetLow)
Definition at line 1134 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getRotationBodyToNED (Matrix3f & mat) const
Definition at line 1054 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::update_EKF2().
void NavEKF2::getTiltError (int8_t instance, float & ang)
Definition at line 870 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getTimingStatistics (int8_t instance, struct ekf_timing & timing)
Definition at line 1480 of file AP_NavEKF2.cpp.
Referenced by have_ekf_logging(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getVariances (int8_t instance, float & velVar, float & posVar, float & hgtVar, Vector3f & magVar, float & tasVar, Vector2f & offset)
Definition at line 1089 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_variances(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getVelNED (int8_t instance, Vector3f & vel)
Definition at line 824 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::get_velocity_NED(), AP_AHRS_NavEKF::groundspeed_vector(), and DataFlash_Class::Log_Write_POS().
void NavEKF2::getWind (int8_t instance, Vector3f & wind)
Definition at line 941 of file AP_NavEKF2.cpp.
Referenced by activeCores(), DataFlash_Class::Log_Write_POS(), and AP_AHRS_NavEKF::wind_estimate().
bool NavEKF2::have_ekf_logging (void) const inline
Definition at line 313 of file AP_NavEKF2.h.
Referenced by check_log_write(), and AP_AHRS_NavEKF::have_ekf_logging().
bool NavEKF2::healthy (void) const
Definition at line 771 of file AP_NavEKF2.cpp.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), activeCores(), AP_AHRS_NavEKF::healthy(), and UpdateFilter().
bool NavEKF2::InitialiseFilter (void)
Definition at line 623 of file AP_NavEKF2.cpp.
Referenced by activeCores(), AP_AHRS_NavEKF::reset(), AP_AHRS_NavEKF::reset_attitude(), and AP_AHRS_NavEKF::update_EKF2().
const char * NavEKF2::prearm_failure_reason (void) const
Definition at line 1353 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::prearm_failure_reason().
void NavEKF2::resetGyroBias (void)
Definition at line 879 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::reset_gyro_drift().
bool NavEKF2::resetHeightDatum (void)
Definition at line 893 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::resetHeightDatum().
void NavEKF2::send_status_report (mavlink_channel_t chan)
Definition at line 1248 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::send_ekf_status_report().
void NavEKF2::set_baro_alt_noise (float noise) inline
Definition at line 307 of file AP_NavEKF2.h.
void NavEKF2::set_enable (bool enable) inline
Definition at line 310 of file AP_NavEKF2.h.
uint8_t NavEKF2::setInhibitGPS (void)
Definition at line 914 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::setInhibitGPS().
bool NavEKF2::setOriginLLH (const Location & loc)
Definition at line 1026 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::set_origin().
void NavEKF2::setTakeoffExpected (bool val)
Definition at line 1146 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::setTakeoffExpected().
void NavEKF2::setTerrainHgtStable (bool val)
Definition at line 1169 of file AP_NavEKF2.cpp.
Referenced by activeCores().
void NavEKF2::setTouchdownExpected (bool val)
Definition at line 1157 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::setTouchdownExpected().
void NavEKF2::UpdateFilter (void)
Definition at line 703 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::update_EKF2().
void NavEKF2::updateLaneSwitchPosDownResetData (uint8_t new_primary, uint8_t old_primary) private
Definition at line 1453 of file AP_NavEKF2.cpp.
Referenced by UpdateFilter().
void NavEKF2::updateLaneSwitchPosResetData (uint8_t new_primary, uint8_t old_primary) private
Definition at line 1426 of file AP_NavEKF2.cpp.
Referenced by UpdateFilter().
void NavEKF2::updateLaneSwitchYawResetData (uint8_t new_primary, uint8_t old_primary) private
Definition at line 1400 of file AP_NavEKF2.cpp.
Referenced by UpdateFilter().
bool NavEKF2::use_compass (void) const
Definition at line 1099 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::use_compass().
void NavEKF2::writeOptFlowMeas (uint8_t & rawFlowQuality, Vector2f & rawFlowRates, Vector2f & rawGyroRates, uint32_t & msecFlowMeas, const Vector3f & posOffset)
Definition at line 1114 of file AP_NavEKF2.cpp.
Referenced by activeCores(), and AP_AHRS_NavEKF::writeOptFlowMeas().
Friends And Related Function Documentation
friend class NavEKF2_core friend
Definition at line 40 of file AP_NavEKF2.h.
Referenced by InitialiseFilter().
Member Data Documentation
AP_Float NavEKF2::_accelBiasProcessNoise private
Definition at line 344 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
AP_Float NavEKF2::_accNoise private
Definition at line 342 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
const AP_AHRS* NavEKF2::_ahrs private
Definition at line 322 of file AP_NavEKF2.h.
Referenced by check_log_write(), InitialiseFilter(), NavEKF2_core::setup_core(), and UpdateFilter().
AP_Int8 NavEKF2::_altSource private
Definition at line 360 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED(), NavEKF2_core::getHeightControlLimit(), NavEKF2_core::selectHeightForFusion(), and NavEKF2_core::updateFilterStatus().
AP_Baro& NavEKF2::_baro private
Definition at line 323 of file AP_NavEKF2.h.
Referenced by check_log_write(), NavEKF2_core::readBaroData(), and NavEKF2_core::resetHeightDatum().
AP_Float NavEKF2::_baroAltNoise private
Definition at line 334 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovarianceInit(), NavEKF2_core::selectHeightForFusion(), and set_baro_alt_noise().
AP_Float NavEKF2::_easNoise private
Definition at line 336 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseAirspeed(), and NavEKF2_core::setWindMagStateLearningMode().
AP_Int8 NavEKF2::_enable private
Definition at line 330 of file AP_NavEKF2.h.
Referenced by InitialiseFilter(), and set_enable().
AP_Int8 NavEKF2::_flowDelay_ms private
Definition at line 357 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::writeOptFlowMeas().
AP_Int16 NavEKF2::_flowInnovGate private
Definition at line 356 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::EstimateTerrainOffset(), and NavEKF2_core::FuseOptFlow().
AP_Float NavEKF2::_flowNoise private
Definition at line 355 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::SelectFlowFusion().
uint8_t NavEKF2::_framesPerPrediction private
Definition at line 327 of file AP_NavEKF2.h.
Referenced by InitialiseFilter(), and UpdateFilter().
uint32_t NavEKF2::_frameTimeUsec private
Definition at line 326 of file AP_NavEKF2.h.
Referenced by InitialiseFilter(), and UpdateFilter().
AP_Int8 NavEKF2::_fusionModeGPS private
Definition at line 347 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::calcGpsGoodToAlign(), NavEKF2_core::FuseVelPosNED(), NavEKF2_core::getHeightControlLimit(), NavEKF2_core::readGpsData(), NavEKF2_core::readyToUseGPS(), NavEKF2_core::ResetHeight(), NavEKF2_core::SelectVelPosFusion(), and NavEKF2_core::setAidingMode().
AP_Int8 NavEKF2::_gpsCheck private
Definition at line 363 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::calcGpsGoodToAlign().
AP_Int16 NavEKF2::_gpsCheckScaler private
Definition at line 365 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::calcGpsGoodToAlign().
AP_Int16 NavEKF2::_gpsDelay_ms private
Definition at line 345 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readGpsData().
AP_Int8 NavEKF2::_gpsGlitchRadiusMax private
Definition at line 354 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED().
AP_Float NavEKF2::_gpsHorizPosNoise private
Definition at line 333 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovarianceInit(), NavEKF2_core::FuseVelPosNED(), NavEKF2_core::ResetPosition(), and NavEKF2_core::selectHeightForFusion().
AP_Float NavEKF2::_gpsHorizVelNoise private
Definition at line 331 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovarianceInit(), NavEKF2_core::FuseVelPosNED(), and NavEKF2_core::ResetVelocity().
AP_Int16 NavEKF2::_gpsPosInnovGate private
Definition at line 349 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED().
AP_Int16 NavEKF2::_gpsVelInnovGate private
Definition at line 348 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED().
AP_Float NavEKF2::_gpsVertVelNoise private
Definition at line 332 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovarianceInit(), NavEKF2_core::FuseVelPosNED(), and NavEKF2_core::ResetHeight().
AP_Float NavEKF2::_gyrNoise private
Definition at line 341 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
AP_Float NavEKF2::_gyroBiasProcessNoise private
Definition at line 343 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
AP_Float NavEKF2::_gyroScaleProcessNoise private
Definition at line 361 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
AP_Int16 NavEKF2::_hgtDelay_ms private
Definition at line 346 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readBaroData().
AP_Int16 NavEKF2::_hgtInnovGate private
Definition at line 350 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED().
AP_Int8 NavEKF2::_imuMask private
Definition at line 364 of file AP_NavEKF2.h.
Referenced by InitialiseFilter().
AP_Int8 NavEKF2::_logging_mask private
Definition at line 367 of file AP_NavEKF2.h.
Referenced by check_log_write(), and have_ekf_logging().
AP_Float NavEKF2::_magBodyProcessNoise private
Definition at line 340 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
AP_Int8 NavEKF2::_magCal private
Definition at line 353 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::effective_magCal().
AP_Float NavEKF2::_magEarthProcessNoise private
Definition at line 339 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
AP_Int16 NavEKF2::_magInnovGate private
Definition at line 351 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseMagnetometer().
AP_Int8 NavEKF2::_magMask private
Definition at line 377 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::effective_magCal().
AP_Float NavEKF2::_magNoise private
Definition at line 335 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::calcQuatAndFieldStates(), NavEKF2_core::FuseMagnetometer(), and NavEKF2_core::setWindMagStateLearningMode().
AP_Float NavEKF2::_maxFlowRate private
Definition at line 359 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::EstimateTerrainOffset(), NavEKF2_core::FuseOptFlow(), and NavEKF2_core::getEkfControlLimits().
AP_Float NavEKF2::_noaidHorizNoise private
Definition at line 366 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED().
AP_Int8 NavEKF2::_originHgtMode private
Definition at line 378 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::getOriginLLH(), NavEKF2_core::getPosD(), and NavEKF2_core::selectHeightForFusion().
const RangeFinder& NavEKF2::_rng private
Definition at line 324 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::getHeightControlLimit(), NavEKF2_core::readRangeFinder(), and NavEKF2_core::selectHeightForFusion().
AP_Int8 NavEKF2::_rngBcnDelay_ms private
Definition at line 375 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readRngBcnData().
AP_Int16 NavEKF2::_rngBcnInnovGate private
Definition at line 374 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseRngBcn().
AP_Float NavEKF2::_rngBcnNoise private
Definition at line 373 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readRngBcnData().
AP_Int16 NavEKF2::_rngInnovGate private
Definition at line 358 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::EstimateTerrainOffset().
AP_Float NavEKF2::_rngNoise private
Definition at line 362 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::EstimateTerrainOffset(), and NavEKF2_core::selectHeightForFusion().
AP_Int16 NavEKF2::_tasInnovGate private
Definition at line 352 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseAirspeed().
AP_Int8 NavEKF2::_tauVelPosOutput private
Definition at line 370 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::calcOutputStates().
AP_Float NavEKF2::_terrGradMax private
Definition at line 372 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::selectHeightForFusion().
AP_Int8 NavEKF2::_useRngSwHgt private
Definition at line 371 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::selectHeightForFusion(), and NavEKF2_core::send_status_report().
AP_Float NavEKF2::_useRngSwSpd private
Definition at line 376 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::selectHeightForFusion().
AP_Float NavEKF2::_windVelProcessNoise private
Definition at line 337 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
AP_Float NavEKF2::_wndVarHgtRateScale private
Definition at line 338 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::CovariancePrediction().
AP_Int16 NavEKF2::_yawInnovGate private
Definition at line 369 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::fuseEulerYaw().
AP_Float NavEKF2::_yawNoise private
Definition at line 368 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::fuseEulerYaw().
const uint16_t NavEKF2::betaAvg_ms private
Definition at line 396 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::SelectBetaFusion().
NavEKF2_core* NavEKF2::core = nullptr private
Definition at line 321 of file AP_NavEKF2.h.
Referenced by getAccelNED(), getAccelZBias(), getActiveMag(), getEkfControlLimits(), getEulerAngles(), getFilterFaults(), getFilterGpsStatus(), getFilterStatus(), getFilterTimeouts(), getFlowDebug(), getGyroBias(), getGyroScaleErrorPercentage(), getHAGL(), getHeightControlLimit(), getInnovations(), getLastPosDownReset(), getLastPosNorthEastReset(), getLastVelNorthEastReset(), getLastYawResetAngle(), getLLH(), getMagNED(), getMagOffsets(), getMagXYZ(), getOriginLLH(), getOutputTrackingError(), getPosD(), getPosDownDerivative(), getPosNE(), getPrimaryCoreIMUIndex(), getPrimaryCoreIndex(), getQuaternion(), getRangeBeaconDebug(), getRotationBodyToNED(), getTiltError(), getTimingStatistics(), getVariances(), getVelNED(), getWind(), healthy(), InitialiseFilter(), prearm_failure_reason(), resetGyroBias(), resetHeightDatum(), send_status_report(), setInhibitGPS(), setOriginLLH(), setTakeoffExpected(), setTerrainHgtStable(), setTouchdownExpected(), UpdateFilter(), updateLaneSwitchPosDownResetData(), updateLaneSwitchPosResetData(), updateLaneSwitchYawResetData(), use_compass(), and writeOptFlowMeas().
bool NavEKF2::core_changed
Definition at line 421 of file AP_NavEKF2.h.
float NavEKF2::core_delta
Definition at line 423 of file AP_NavEKF2.h.
Vector2f NavEKF2::core_delta
Definition at line 430 of file AP_NavEKF2.h.
const float NavEKF2::covDelAngMax private
Definition at line 398 of file AP_NavEKF2.h.
const float NavEKF2::covTimeStepMax private
Definition at line 397 of file AP_NavEKF2.h.
const float NavEKF2::DCM33FlowMin private
Definition at line 399 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::SelectFlowFusion().
bool NavEKF2::enabled
Definition at line 409 of file AP_NavEKF2.h.
const uint32_t NavEKF2::flowIntervalMax_ms private
Definition at line 402 of file AP_NavEKF2.h.
const uint8_t NavEKF2::flowTimeDeltaAvg_ms private
Definition at line 401 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::writeOptFlowMeas().
const float NavEKF2::fScaleFactorPnoise private
Definition at line 400 of file AP_NavEKF2.h.
const uint8_t NavEKF2::fusionTimeStep_ms private
Definition at line 406 of file AP_NavEKF2.h.
const float NavEKF2::gndEffectBaroScaler private
Definition at line 404 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::selectHeightForFusion().
const uint16_t NavEKF2::gndEffectTimeout_ms private
Definition at line 403 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::getTakeoffExpected(), and NavEKF2_core::getTouchdownExpected().
const uint8_t NavEKF2::gndGradientSigma private
Definition at line 405 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::EstimateTerrainOffset().
const float NavEKF2::gpsDVelVarAccScale private
Definition at line 382 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED().
const float NavEKF2::gpsNEVelVarAccScale private
Definition at line 381 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED().
const float NavEKF2::gpsPosVarAccScale private
Definition at line 383 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseVelPosNED().
const float NavEKF2::gyroBiasNoiseScaler private
Definition at line 394 of file AP_NavEKF2.h.
const uint16_t NavEKF2::hgtAvg_ms private
Definition at line 395 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::selectHeightForFusion().
const uint16_t NavEKF2::hgtRetryTimeMode0_ms private
Definition at line 389 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::selectHeightForFusion().
const uint16_t NavEKF2::hgtRetryTimeMode12_ms private
Definition at line 390 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::selectHeightForFusion().
uint64_t NavEKF2::imuSampleTime_us private
Definition at line 417 of file AP_NavEKF2.h.
Referenced by check_log_write(), getLastPosDownReset(), getLastPosNorthEastReset(), getLastYawResetAngle(), InitialiseFilter(), NavEKF2_core::InitialiseVariables(), UpdateFilter(), NavEKF2_core::UpdateFilter(), updateLaneSwitchPosDownResetData(), updateLaneSwitchPosResetData(), and updateLaneSwitchYawResetData().
uint32_t NavEKF2::last_function_call
Definition at line 420 of file AP_NavEKF2.h.
uint32_t NavEKF2::last_primary_change
Definition at line 422 of file AP_NavEKF2.h.
bool NavEKF2::log_baro
Definition at line 412 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readBaroData().
bool NavEKF2::log_compass
Definition at line 410 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readMagData().
bool NavEKF2::log_gps
Definition at line 411 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readGpsData().
bool NavEKF2::log_imu
Definition at line 413 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readDeltaAngle().
struct { ... } NavEKF2::logging
Referenced by check_log_write(), have_ekf_logging(), InitialiseFilter(), NavEKF2_core::readBaroData(), NavEKF2_core::readDeltaAngle(), NavEKF2_core::readGpsData(), and NavEKF2_core::readMagData().
const uint16_t NavEKF2::magDelay_ms private
Definition at line 384 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readMagData().
const uint32_t NavEKF2::magFailTimeLimit_ms private
Definition at line 392 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::SelectMagFusion().
const float NavEKF2::magVarRateScale private
Definition at line 393 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseMagnetometer().
uint8_t NavEKF2::num_cores private
Definition at line 319 of file AP_NavEKF2.h.
Referenced by activeCores(), getAccelZBias(), getActiveMag(), getEulerAngles(), getFilterFaults(), getFilterGpsStatus(), getFilterStatus(), getFilterTimeouts(), getFlowDebug(), getGyroBias(), getGyroScaleErrorPercentage(), getInnovations(), getMagNED(), getMagOffsets(), getMagXYZ(), getOriginLLH(), getOutputTrackingError(), getPosD(), getPosDownDerivative(), getPosNE(), getQuaternion(), getRangeBeaconDebug(), getTiltError(), getTimingStatistics(), getVariances(), getVelNED(), getWind(), InitialiseFilter(), resetGyroBias(), resetHeightDatum(), setTakeoffExpected(), setTerrainHgtStable(), setTouchdownExpected(), UpdateFilter(), and writeOptFlowMeas().
struct { ... } NavEKF2::pos_down_reset_data
Referenced by getLastPosDownReset(), InitialiseFilter(), and updateLaneSwitchPosDownResetData().
struct { ... } NavEKF2::pos_reset_data
Referenced by getLastPosNorthEastReset(), InitialiseFilter(), and updateLaneSwitchPosResetData().
const uint16_t NavEKF2::posRetryTimeNoVel_ms private
Definition at line 388 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::SelectBetaFusion(), and NavEKF2_core::setAidingMode().
const uint16_t NavEKF2::posRetryTimeUseVel_ms private
Definition at line 387 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::setAidingMode().
uint8_t NavEKF2::primary private
Definition at line 320 of file AP_NavEKF2.h.
Referenced by getAccelNED(), getAccelZBias(), getActiveMag(), getEkfControlLimits(), getEulerAngles(), getFilterFaults(), getFilterGpsStatus(), getFilterStatus(), getFilterTimeouts(), getFlowDebug(), getGyroBias(), getGyroScaleErrorPercentage(), getHAGL(), getHeightControlLimit(), getInnovations(), getLastPosDownReset(), getLastPosNorthEastReset(), getLastVelNorthEastReset(), getLastYawResetAngle(), getLLH(), getMagNED(), getMagOffsets(), getMagXYZ(), getOriginLLH(), getOutputTrackingError(), getPosD(), getPosDownDerivative(), getPosNE(), getPrimaryCoreIMUIndex(), getPrimaryCoreIndex(), getQuaternion(), getRangeBeaconDebug(), getRotationBodyToNED(), getTiltError(), getTimingStatistics(), getVariances(), getVelNED(), getWind(), healthy(), InitialiseFilter(), prearm_failure_reason(), send_status_report(), setInhibitGPS(), setOriginLLH(), UpdateFilter(), and use_compass().
bool NavEKF2::runCoreSelection private
Definition at line 440 of file AP_NavEKF2.h.
Referenced by UpdateFilter().
const uint16_t NavEKF2::tasDelay_ms private
Definition at line 385 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::readAirSpdData().
const uint16_t NavEKF2::tasRetryTime_ms private
Definition at line 391 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::FuseAirspeed(), and NavEKF2_core::SelectTasFusion().
const uint16_t NavEKF2::tiltDriftTimeMax_ms private
Definition at line 386 of file AP_NavEKF2.h.
Referenced by NavEKF2_core::setAidingMode().
const AP_Param::GroupInfo NavEKF2::var_info static
Definition at line 41 of file AP_NavEKF2.h.
Referenced by NavEKF2().
struct { ... } NavEKF2::yaw_reset_data
Referenced by getLastYawResetAngle(), InitialiseFilter(), and updateLaneSwitchYawResetData().
The documentation for this class was generated from the following files:
libraries/AP_NavEKF2/AP_NavEKF2.h
libraries/AP_NavEKF2/AP_NavEKF2.cpp