APM:Libraries: GCS Class Reference
GCS Class Reference abstract
global GCS object
#include <GCS.h>
Classes
struct statustext_t
Public Member Functions
GCS ()
void send_text (MAV_SEVERITY severity, const char *fmt,...)
virtual void send_statustext (MAV_SEVERITY severity, uint8_t dest_bitmask, const char *text)
void service_statustext (void)
virtual GCS_MAVLINK & chan (const uint8_t ofs)=0
virtual const GCS_MAVLINK & chan (const uint8_t ofs) const =0
virtual uint8_t num_gcs () const =0
void reset_cli_timeout ()
void send_message (enum ap_message id)
void send_mission_item_reached_message (uint16_t mission_index)
void send_home (const Location &home) const
void data_stream_send ()
void update ()
virtual void setup_uarts (AP_SerialManager &serial_manager)
void handle_interactive_setup ()
FUNCTOR_TYPEDEF (run_cli_fn, void, AP_HAL::UARTDriver *)
void set_run_cli_func (run_cli_fn run_cli)
void set_dataflash (DataFlash_Class *dataflash)
void register_frsky_telemetry_callback (AP_Frsky_Telem *frsky_telemetry)
Static Public Member Functions
static class GCS * instance ()
Public Attributes
run_cli_fn _run_cli
DataFlash_Class * dataflash_p
AP_Frsky_Telem * frsky_telemetry_p
Private Member Functions
virtual bool cli_enabled () const =0
virtual AP_HAL::BetterStream * cliSerial ()=0
Private Attributes
ObjectArray< statustext_t > _statustext_queue {_status_capacity}
Static Private Attributes
static GCS * _singleton = nullptr
static const uint8_t _status_capacity = 5
Detailed Description
global GCS object
Definition at line 425 of file GCS.h.
Constructor & Destructor Documentation
GCS::GCS () inline
Definition at line 430 of file GCS.h.
Member Function Documentation
virtual GCS_MAVLINK& GCS::chan (const uint8_t ofs) pure virtual
Implemented in GCS_Dummy.
virtual const GCS_MAVLINK& GCS::chan (const uint8_t ofs) const pure virtual
Implemented in GCS_Dummy.
virtual bool GCS::cli_enabled () const private pure virtual
Implemented in GCS_Dummy.
virtual AP_HAL::BetterStream* GCS::cliSerial () private pure virtual
Implemented in GCS_Dummy.
void GCS::data_stream_send (void)
Definition at line 1282 of file GCS_Common.cpp.
GCS::FUNCTOR_TYPEDEF (run_cli_fn , void , AP_HAL::UARTDriver *)
void GCS::handle_interactive_setup ()
Definition at line 1317 of file GCS_Common.cpp.
Referenced by instance().
static class GCS* GCS::instance (void) inline static
Definition at line 442 of file GCS.h.
Referenced by gcs().
virtual uint8_t GCS::num_gcs () const pure virtual
Implemented in GCS_Dummy.
void GCS::register_frsky_telemetry_callback (AP_Frsky_Telem * frsky_telemetry) inline
Definition at line 479 of file GCS.h.
Referenced by AP_Frsky_Telem::init().
void GCS::reset_cli_timeout ()
Definition at line 1266 of file GCS_Common.cpp.
void GCS::send_home (const Location & home) const
Definition at line 32 of file GCS.cpp.
void GCS::send_message (enum ap_message id)
Definition at line 1273 of file GCS_Common.cpp.
Referenced by AP_Camera::log_picture(), and AP_Camera::update_trigger().
void GCS::send_mission_item_reached_message (uint16_t mission_index)
Definition at line 1300 of file GCS_Common.cpp.
Referenced by instance().
void GCS::send_statustext (MAV_SEVERITY severity, uint8_t dest_bitmask, const char * text) virtual
Reimplemented in GCS_Dummy.
Definition at line 1182 of file GCS_Common.cpp.
Referenced by instance(), GCS_MAVLINK::send_text(), and send_text().
void GCS::send_text (MAV_SEVERITY severity, const char * fmt, ...)
Definition at line 8 of file GCS.cpp.
Referenced by AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_save_cfg(), AP_Arming::airspeed_checks(), AP_Arming::arm(), AP_Arming::arm_checks(), AP_Arming::barometer_checks(), AP_Arming::battery_checks(), AP_Arming::board_voltage_checks(), AP_GPS_SBF::broadcast_configuration_failure_reason(), AP_GPS_UBLOX::broadcast_configuration_failure_reason(), AP_GPS::broadcast_first_configuration_failure_reason(), AP_GPS_Backend::broadcast_gps_type(), AP_Landing_Deepstall::build_approach_path(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_AdvancedFailsafe::check(), AP_Tuning::check_controller_error(), SoaringController::check_cruise_criteria(), AP_Tuning::check_input(), AP_Tuning::check_selector_switch(), NavEKF2_core::checkAttitudeAlignmentStatus(), NavEKF3_core::checkAttitudeAlignmentStatus(), AP_Arming::compass_checks(), NavEKF2_core::controlMagYawReset(), NavEKF3_core::controlMagYawReset(), AP_Arming::disarm(), AP_ICEngine::engine_control(), NavEKF3_core::FuseBodyVel(), NavEKF3_core::FuseOptFlow(), AP_Arming::gps_checks(), AP_ADSB::handle_transceiver_report(), AP_Arming::hardware_safety_check(), AP_MotorsTri::init(), AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_Airspeed::init(), DataFlash_Class::Init(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), NavEKF3_core::InitialiseFilterBootstrap(), AP_Arming::ins_checks(), AP_Mission::jump_to_landing_sequence(), AP_Arming::logging_checks(), AP_Arming::manual_transmitter_checks(), AP_Tuning::next_parameter(), AP_Landing_Deepstall::override_servos(), AP_MotorsHeli::parameter_check(), AP_MotorsHeli_Single::parameter_check(), AP_Landing_Deepstall::predict_travel_distance(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), AP_Landing::restart_landing_sequence(), AP_BoardConfig::sensor_config_error(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), NavEKF3_core::setup_core(), AP_Camera::setup_feedback_callback(), AP_Landing::type_slope_adjust_landing_slope_for_rangefinder_bump(), AP_Landing::type_slope_do_land(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_Landing::type_slope_verify_land(), AP_ICEngine::update(), AP_ADSB::update(), AP_Airspeed::update_calibration(), AP_Landing_Deepstall::update_steering(), SoaringController::update_thermalling(), and AP_Landing::verify_land().
void GCS::service_statustext (void)
Definition at line 1221 of file GCS_Common.cpp.
Referenced by instance().
void GCS::set_dataflash (DataFlash_Class * dataflash) inline
Definition at line 468 of file GCS.h.
void GCS::set_run_cli_func (run_cli_fn run_cli) inline
Definition at line 463 of file GCS.h.
void GCS::setup_uarts (AP_SerialManager & serial_manager) virtual
Definition at line 1310 of file GCS_Common.cpp.
Referenced by instance().
void GCS::update (void)
Definition at line 1291 of file GCS_Common.cpp.
Member Data Documentation
run_cli_fn GCS::_run_cli
Definition at line 462 of file GCS.h.
GCS * GCS::_singleton = nullptr static private
Definition at line 488 of file GCS.h.
Referenced by instance().
const uint8_t GCS::_status_capacity = 5 static private
Definition at line 499 of file GCS.h.
ObjectArray<statustext_t> GCS::_statustext_queue {_status_capacity} private
Definition at line 504 of file GCS.h.
DataFlash_Class* GCS::dataflash_p
Definition at line 473 of file GCS.h.
Referenced by set_dataflash().
AP_Frsky_Telem* GCS::frsky_telemetry_p
Definition at line 484 of file GCS.h.
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS_Common.cpp