APM:Libraries: AP_VisualOdom_Backend Class Reference
AP_VisualOdom_Backend Class Reference
#include <AP_VisualOdom_Backend.h>
Public Member Functions
AP_VisualOdom_Backend (AP_VisualOdom &frontend)
virtual void handle_msg (mavlink_message_t *msg)
Protected Member Functions
void set_deltas (const Vector3f &angle_delta, const Vector3f &position_delta, uint64_t time_delta_usec, float confidence)
Private Attributes
AP_VisualOdom & _frontend
Detailed Description
Definition at line 21 of file AP_VisualOdom_Backend.h.
Constructor & Destructor Documentation
AP_VisualOdom_Backend::AP_VisualOdom_Backend (AP_VisualOdom & frontend)
Definition at line 22 of file AP_VisualOdom_Backend.cpp.
Member Function Documentation
virtual void AP_VisualOdom_Backend::handle_msg (mavlink_message_t * msg) inline virtual
Reimplemented in AP_VisualOdom_MAV.
Definition at line 28 of file AP_VisualOdom_Backend.h.
Referenced by AP_VisualOdom::handle_msg().
void AP_VisualOdom_Backend::set_deltas (const Vector3f & angle_delta, const Vector3f & position_delta, uint64_t time_delta_usec, float confidence) protected
Definition at line 28 of file AP_VisualOdom_Backend.cpp.
Referenced by AP_VisualOdom_MAV::handle_msg(), and handle_msg().
Member Data Documentation
AP_VisualOdom& AP_VisualOdom_Backend::_frontend private
Definition at line 38 of file AP_VisualOdom_Backend.h.
Referenced by set_deltas().
The documentation for this class was generated from the following files:
libraries/AP_VisualOdom/AP_VisualOdom_Backend.h
libraries/AP_VisualOdom/AP_VisualOdom_Backend.cpp