APM:Libraries: AP_BattMonitor_Backend Class Reference
AP_BattMonitor_Backend Class Reference abstract
#include <AP_BattMonitor_Backend.h>
Public Member Functions
AP_BattMonitor_Backend (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state)
virtual ~AP_BattMonitor_Backend (void)
virtual void init ()
virtual void read ()=0
virtual bool has_current () const =0
returns true if battery monitor instance provides current info
virtual bool has_cell_voltages () const
uint8_t capacity_remaining_pct () const
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
int32_t get_capacity () const
get capacity for this instance
void update_resistance_estimate ()
Protected Attributes
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
Private Attributes
uint32_t _resistance_timer_ms
float _voltage_filt
float _current_max_amps
float _current_filt_amps
float _resistance_voltage_ref
float _resistance_current_ref
Detailed Description
Definition at line 21 of file AP_BattMonitor_Backend.h.
Constructor & Destructor Documentation
AP_BattMonitor_Backend::AP_BattMonitor_Backend (AP_BattMonitor & mon, AP_BattMonitor::BattMonitor_State & mon_state)
Definition at line 25 of file AP_BattMonitor_Backend.cpp.
virtual AP_BattMonitor_Backend::~AP_BattMonitor_Backend (void) inline virtual
Definition at line 29 of file AP_BattMonitor_Backend.h.
Member Function Documentation
uint8_t AP_BattMonitor_Backend::capacity_remaining_pct () const
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
Definition at line 32 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor::capacity_remaining_pct(), and has_cell_voltages().
int32_t AP_BattMonitor_Backend::get_capacity () const
get capacity for this instance
Definition at line 43 of file AP_BattMonitor_Backend.cpp.
Referenced by has_cell_voltages(), and AP_BattMonitor_SMBus::read_remaining_capacity().
virtual bool AP_BattMonitor_Backend::has_cell_voltages () const inline virtual
Reimplemented in AP_BattMonitor_SMBus.
Definition at line 41 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor::has_cell_voltages().
virtual bool AP_BattMonitor_Backend::has_current () const pure virtual
returns true if battery monitor instance provides current info
Implemented in AP_BattMonitor_Analog, AP_BattMonitor_Bebop, and AP_BattMonitor_SMBus.
Referenced by AP_BattMonitor::has_current(), init(), and update_resistance_estimate().
virtual void AP_BattMonitor_Backend::init (void) inline virtual
Reimplemented in AP_BattMonitor_Bebop.
Definition at line 32 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor::init().
virtual void AP_BattMonitor_Backend::read () pure virtual
Implemented in AP_BattMonitor_Analog, AP_BattMonitor_Bebop, and AP_BattMonitor_SMBus.
Referenced by init(), and AP_BattMonitor::read().
void AP_BattMonitor_Backend::update_resistance_estimate ()
Definition at line 52 of file AP_BattMonitor_Backend.cpp.
Referenced by has_cell_voltages(), and AP_BattMonitor::read().
Member Data Documentation
float AP_BattMonitor_Backend::_current_filt_amps private
Definition at line 61 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
float AP_BattMonitor_Backend::_current_max_amps private
Definition at line 60 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
AP_BattMonitor& AP_BattMonitor_Backend::_mon protected
Definition at line 53 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor_SMBus::AP_BattMonitor_SMBus(), capacity_remaining_pct(), get_capacity(), AP_BattMonitor_Analog::has_current(), AP_BattMonitor_SMBus::read(), and AP_BattMonitor_Analog::read().
float AP_BattMonitor_Backend::_resistance_current_ref private
Definition at line 63 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
uint32_t AP_BattMonitor_Backend::_resistance_timer_ms private
Definition at line 58 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
float AP_BattMonitor_Backend::_resistance_voltage_ref private
Definition at line 62 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
AP_BattMonitor::BattMonitor_State& AP_BattMonitor_Backend::_state protected
Definition at line 54 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor_Analog::AP_BattMonitor_Analog(), AP_BattMonitor_SMBus::AP_BattMonitor_SMBus(), capacity_remaining_pct(), get_capacity(), AP_BattMonitor_Analog::has_current(), AP_BattMonitor_SMBus::read(), AP_BattMonitor_Analog::read(), AP_BattMonitor_SMBus::read_remaining_capacity(), AP_BattMonitor_SMBus::read_temp(), AP_BattMonitor_SMBus_Maxell::timer(), AP_BattMonitor_SMBus_Solo::timer(), and update_resistance_estimate().
float AP_BattMonitor_Backend::_voltage_filt private
Definition at line 59 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_Backend.h
libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp