APM:Libraries: AP_AHRS Class Reference
AP_AHRS Class Reference abstract
#include <AP_AHRS.h>
Classes
struct ahrs_flags
Public Member Functions
AP_AHRS (AP_InertialSensor &ins, AP_Baro &baro, AP_GPS &gps)
virtual ~AP_AHRS ()
virtual void init ()
void set_fly_forward (bool b)
bool get_fly_forward (void) const
void set_likely_flying (bool b)
bool get_likely_flying (void) const
uint32_t get_time_flying_ms (void) const
AHRS_VehicleClass get_vehicle_class (void) const
void set_vehicle_class (AHRS_VehicleClass vclass)
void set_wind_estimation (bool b)
void set_compass (Compass *compass)
const Compass * get_compass () const
void set_optflow (const OpticalFlow *optflow)
const OpticalFlow * get_optflow () const
void set_orientation ()
void set_airspeed (AP_Airspeed *airspeed)
void set_beacon (AP_Beacon *beacon)
const AP_Airspeed * get_airspeed (void) const
const AP_Beacon * get_beacon (void) const
const AP_GPS & get_gps () const
const AP_InertialSensor & get_ins () const
const AP_Baro & get_baro () const
virtual uint8_t get_primary_accel_index (void) const
virtual uint8_t get_primary_gyro_index (void) const
virtual const Vector3f & get_accel_ef (uint8_t i) const
virtual const Vector3f & get_accel_ef (void) const
virtual const Vector3f & get_accel_ef_blended (void) const
float get_yaw_rate_earth (void) const
virtual void update (bool skip_ins_update=false)=0
virtual const char * prearm_failure_reason (void) const
virtual bool have_ekf_logging (void) const
virtual const Vector3f & get_gyro (void) const =0
Vector3f get_gyro_latest (void) const
virtual const Vector3f & get_gyro_drift (void) const =0
virtual void reset_gyro_drift (void)=0
virtual void reset (bool recover_eulers=false)=0
virtual void reset_attitude (const float &roll, const float &pitch, const float &yaw)=0
virtual float get_error_rp (void) const =0
virtual float get_error_yaw (void) const =0
virtual const Matrix3f & get_rotation_body_to_ned (void) const =0
const Matrix3f & get_rotation_autopilot_body_to_vehicle_body (void) const
const Matrix3f & get_rotation_vehicle_body_to_autopilot_body (void) const
virtual bool get_position (struct Location &loc) const =0
virtual Vector3f wind_estimate (void)=0
virtual bool airspeed_estimate (float *airspeed_ret) const
bool airspeed_estimate_true (float *airspeed_ret) const
float get_EAS2TAS (void) const
bool airspeed_sensor_enabled (void) const
virtual Vector2f groundspeed_vector (void)
virtual bool get_velocity_NED (Vector3f &vec) const
virtual bool get_expected_mag_field_NED (Vector3f &ret) const
virtual bool get_mag_field_correction (Vector3f &ret) const
virtual bool get_relative_position_NED_home (Vector3f &vec) const
virtual bool get_relative_position_NED_origin (Vector3f &vec) const
virtual bool get_relative_position_NE_home (Vector2f &vecNE) const
virtual bool get_relative_position_NE_origin (Vector2f &vecNE) const
virtual void get_relative_position_D_home (float &posD) const =0
virtual bool get_relative_position_D_origin (float &posD) const
float groundspeed (void)
virtual bool use_compass (void)
bool yaw_initialised (void) const
void set_correct_centrifugal (bool setting)
bool get_correct_centrifugal (void) const
const Vector3f & get_trim () const
virtual void set_trim (Vector3f new_trim)
virtual void add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom=true)
float cos_roll () const
float cos_pitch () const
float cos_yaw () const
float sin_roll () const
float sin_pitch () const
float sin_yaw () const
virtual bool get_secondary_attitude (Vector3f &eulers)
virtual bool get_secondary_quaternion (Quaternion &quat)
virtual bool get_secondary_position (struct Location &loc)
const struct Location & get_home (void) const
virtual void set_home (const Location &loc)=0
virtual bool set_origin (const Location &loc)
virtual bool have_inertial_nav (void) const
uint8_t get_active_accel_instance (void) const
virtual bool healthy (void) const =0
virtual bool initialised (void) const
virtual uint32_t getLastYawResetAngle (float &yawAng) const
virtual uint32_t getLastPosNorthEastReset (Vector2f &pos) const
virtual uint32_t getLastVelNorthEastReset (Vector2f &vel) const
virtual uint32_t getLastPosDownReset (float &posDelta) const
virtual bool resetHeightDatum (void)
virtual bool get_variances (float &velVar, float &posVar, float &hgtVar, Vector3f &magVar, float &tasVar, Vector2f &offset) const
virtual uint32_t uptime_ms (void) const =0
int8_t get_ekf_type (void) const
virtual void getCorrectedDeltaVelocityNED (Vector3f &ret, float &dt) const
AP_AHRS_View * create_view (enum Rotation rotation)
float getAOA (void)
float getSSA (void)
virtual void update_AOA_SSA (void)
Public Attributes
float roll
float pitch
float yaw
int32_t roll_sensor
int32_t pitch_sensor
int32_t yaw_sensor
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void calc_trig (const Matrix3f &rot, float &cr, float &cp, float &cy, float &sr, float &sp, float &sy) const
void update_trig (void)
void update_cd_values (void)
Protected Attributes
AHRS_VehicleClass _vehicle_class
AP_Float _kp_yaw
AP_Float _kp
AP_Float gps_gain
AP_Float beta
AP_Int8 _gps_use
AP_Int8 _wind_max
AP_Int8 _board_orientation
AP_Int8 _gps_minsats
AP_Int8 _gps_delay
AP_Int8 _ekf_type
struct AP_AHRS::ahrs_flags _flags
uint32_t _last_flying_ms
Compass * _compass
const OpticalFlow * _optflow
AP_Airspeed * _airspeed
AP_Beacon * _beacon
uint32_t _compass_last_update
AP_InertialSensor & _ins
AP_Baro & _baro
const AP_GPS & _gps
AP_Vector3f _trim
Vector3f _last_trim
Matrix3f _rotation_autopilot_body_to_vehicle_body
Matrix3f _rotation_vehicle_body_to_autopilot_body
float _gyro_drift_limit
Vector3f _accel_ef [INS_MAX_INSTANCES]
Vector3f _accel_ef_blended
Vector2f _lp
Vector2f _hp
Vector2f _lastGndVelADS
struct Location _home
float _cos_roll
float _cos_pitch
float _cos_yaw
float _sin_roll
float _sin_pitch
float _sin_yaw
uint8_t _active_accel_instance
AP_AHRS_View * _view
float _AOA
float _SSA
uint32_t _last_AOA_update_ms
Friends
class AP_AHRS_View
Detailed Description
Definition at line 50 of file AP_AHRS.h.
Constructor & Destructor Documentation
AP_AHRS::AP_AHRS (AP_InertialSensor & ins, AP_Baro & baro, AP_GPS & gps) inline
Definition at line 56 of file AP_AHRS.h.
virtual AP_AHRS::~AP_AHRS () inline virtual
Definition at line 102 of file AP_AHRS.h.
Member Function Documentation
void AP_AHRS::add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom = true) virtual
Definition at line 171 of file AP_AHRS.cpp.
Referenced by get_trim().
bool AP_AHRS::airspeed_estimate (float * airspeed_ret) const virtual
Reimplemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Definition at line 142 of file AP_AHRS.cpp.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_TECS::_update_speed(), AP_AHRS_View::airspeed_estimate(), airspeed_estimate_true(), AP_PitchController::get_rate_out(), get_rotation_vehicle_body_to_autopilot_body(), AP_YawController::get_servo_out(), AP_Landing_Deepstall::override_servos(), and Variometer::update().
bool AP_AHRS::airspeed_estimate_true (float * airspeed_ret) const inline
Definition at line 313 of file AP_AHRS.h.
Referenced by AP_AHRS_View::airspeed_estimate_true(), and groundspeed_vector().
bool AP_AHRS::airspeed_sensor_enabled (void) const inline
Definition at line 331 of file AP_AHRS.h.
Referenced by AP_TECS::_update_pitch(), AP_TECS::_update_speed(), AP_AHRS_DCM::airspeed_estimate(), airspeed_estimate(), NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), NavEKF3_core::setup_core(), AP_TECS::update_pitch_throttle(), NavEKF2_core::useAirspeed(), and NavEKF3_core::useAirspeed().
void AP_AHRS::calc_trig (const Matrix3f & rot, float & cr, float & cp, float & cy, float & sr, float & sp, float & sy) const protected
Definition at line 244 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::update(), and update_trig().
float AP_AHRS::cos_pitch () const inline
Definition at line 431 of file AP_AHRS.h.
float AP_AHRS::cos_roll () const inline
Definition at line 428 of file AP_AHRS.h.
float AP_AHRS::cos_yaw () const inline
Definition at line 434 of file AP_AHRS.h.
Referenced by AC_Avoid::adjust_velocity_polygon().
AP_AHRS_View * AP_AHRS::create_view (enum Rotation rotation)
Definition at line 320 of file AP_AHRS.cpp.
Referenced by getCorrectedDeltaVelocityNED().
virtual const Vector3f& AP_AHRS::get_accel_ef (uint8_t i) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 227 of file AP_AHRS.h.
Referenced by AP_TECS::update_50hz().
virtual const Vector3f& AP_AHRS::get_accel_ef (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 230 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::get_accel_ef().
virtual const Vector3f& AP_AHRS::get_accel_ef_blended (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 235 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::get_accel_ef_blended(), AP_AHRS_View::get_accel_ef_blended(), and DataFlash_Class::Log_Write_Rate().
uint8_t AP_AHRS::get_active_accel_instance (void) const inline
Definition at line 488 of file AP_AHRS.h.
const AP_Airspeed* AP_AHRS::get_airspeed (void) const inline
Definition at line 196 of file AP_AHRS.h.
Referenced by AP_Arming::airspeed_checks(), AP_Frsky_Telem::calc_velandyaw(), NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), NavEKF2_core::readAirSpdData(), and NavEKF3_core::readAirSpdData().
const AP_Baro& AP_AHRS::get_baro () const inline
Definition at line 212 of file AP_AHRS.h.
Referenced by AP_ADSB::send_dynamic_out(), and AP_TECS::update_50hz().
const AP_Beacon* AP_AHRS::get_beacon (void) const inline
Definition at line 200 of file AP_AHRS.h.
Referenced by DataFlash_Class::Log_Write_POS(), NavEKF2_core::readRngBcnData(), and NavEKF3_core::readRngBcnData().
const Compass* AP_AHRS::get_compass () const inline
Definition at line 167 of file AP_AHRS.h.
Referenced by NavEKF2_core::alignMagStateDeclination(), NavEKF3_core::alignMagStateDeclination(), SoloGimbalEKF::calcMagHeadingInnov(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcQuatAndFieldStates(), NavEKF3::check_log_write(), NavEKF2::check_log_write(), NavEKF2_core::FuseDeclination(), NavEKF3_core::FuseDeclination(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), NavEKF2_core::getMagOffsets(), NavEKF3_core::getMagOffsets(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), SoloGimbalEKF::readMagData(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), NavEKF2_core::use_compass(), and NavEKF3_core::use_compass().
bool AP_AHRS::get_correct_centrifugal (void) const inline
Definition at line 412 of file AP_AHRS.h.
float AP_AHRS::get_EAS2TAS (void) const inline
Definition at line 322 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_PitchController::_get_rate_out(), AP_RollController::_get_rate_out(), AP_TECS::_update_speed(), AP_AHRS_DCM::airspeed_estimate(), airspeed_estimate(), airspeed_estimate_true(), AP_AHRS_DCM::estimate_wind(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), AP_AHRS_View::get_EAS2TAS(), AP_TECS::get_target_airspeed(), AP_L1_Control::loiter_radius(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), and AP_L1_Control::turn_distance().
int8_t AP_AHRS::get_ekf_type (void) const inline
Definition at line 545 of file AP_AHRS.h.
virtual float AP_AHRS::get_error_rp (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_AHRS_View::get_error_rp(), DataFlash_Class::Log_Write_Attitude(), and GCS_MAVLINK::send_ahrs().
virtual float AP_AHRS::get_error_yaw (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_AHRS_View::get_error_yaw(), DataFlash_Class::Log_Write_Attitude(), and GCS_MAVLINK::send_ahrs().
virtual bool AP_AHRS::get_expected_mag_field_NED (Vector3f & ret) const inline virtual
Definition at line 346 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_expected_mag_field_NED().
bool AP_AHRS::get_fly_forward (void) const inline
Definition at line 114 of file AP_AHRS.h.
Referenced by NavEKF2_core::assume_zero_sideslip(), and NavEKF3_core::assume_zero_sideslip().
const AP_GPS& AP_AHRS::get_gps () const inline
Definition at line 204 of file AP_AHRS.h.
Referenced by AP_Frsky_Telem::calc_gps_latlng(), AP_Frsky_Telem::calc_gps_position(), AP_Frsky_Telem::calc_gps_status(), NavEKF2_core::calcGpsGoodForFlight(), NavEKF3_core::calcGpsGoodForFlight(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), NavEKF3::check_log_write(), NavEKF2::check_log_write(), AP_ADSB::genICAO(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), NavEKF2_core::getPosNE(), NavEKF3_core::getPosNE(), AP_Arming::gps_checks(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), NavEKF2_core::SelectVelPosFusion(), NavEKF3_core::SelectVelPosFusion(), AP_Frsky_Telem::send_D(), AP_ADSB::send_dynamic_out(), AP_Frsky_Telem::send_SPort(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), NavEKF3_core::setup_core(), and AP_Landing::type_slope_verify_land().
virtual const Vector3f& AP_AHRS::get_gyro (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_PitchController::_get_rate_out(), AP_RollController::_get_rate_out(), AP_YawController::get_servo_out(), get_yaw_rate_earth(), DataFlash_Class::Log_Write_Rate(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), AP_AHRS_View::update(), and AP_Landing_Deepstall::update_steering().
virtual const Vector3f& AP_AHRS::get_gyro_drift (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by get_gyro_latest(), and GCS_MAVLINK::send_ahrs().
Vector3f AP_AHRS::get_gyro_latest (void) const
Definition at line 135 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::get_gyro_latest().
const struct Location& AP_AHRS::get_home (void) const inline
Definition at line 467 of file AP_AHRS.h.
Referenced by AP_Rally::calc_best_rally_or_home_location(), AP_Frsky_Telem::calc_home(), AP_Frsky_Telem::calc_nav_alt(), AC_Fence::check_destination_within_fence(), AP_Rally::find_nearest_rally_point(), AC_Avoid::get_alt_above_home(), Location_Class::get_alt_cm(), AP_AHRS_NavEKF::get_hagl(), AC_Avoid::get_position(), AP_AHRS_NavEKF::get_relative_position_D_origin(), AP_AHRS_NavEKF::get_relative_position_NE_origin(), AP_AHRS_NavEKF::get_relative_position_NED_origin(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), DataFlash_Class::Log_Write_CameraInfo(), AP_Rally::rally_location_to_location(), AP_Mission::read_cmd_from_storage(), AP_Camera::send_feedback(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), NavEKF2_core::setOriginLLH(), NavEKF3_core::setOriginLLH(), and AP_Mission::write_home_to_storage().
const AP_InertialSensor& AP_AHRS::get_ins () const inline
Definition at line 208 of file AP_AHRS.h.
Referenced by NavEKF3::check_log_write(), NavEKF2::check_log_write(), AC_PrecLand::construct_pos_meas_using_rangefinder(), NavEKF2_core::detectOptFlowTakeoff(), NavEKF3_core::detectOptFlowTakeoff(), get_gyro_latest(), AP_YawController::get_servo_out(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), AP_Arming::ins_checks(), NavEKF2_core::readDeltaAngle(), NavEKF3_core::readDeltaAngle(), NavEKF2_core::readDeltaVelocity(), NavEKF3_core::readDeltaVelocity(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), AC_PrecLand::run_output_prediction(), NavEKF2_core::setup_core(), NavEKF3_core::setup_core(), AP_TECS::update_50hz(), NavEKF3::UpdateFilter(), and NavEKF2::UpdateFilter().
bool AP_AHRS::get_likely_flying (void) const inline
Definition at line 135 of file AP_AHRS.h.
virtual bool AP_AHRS::get_mag_field_correction (Vector3f & ret) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 351 of file AP_AHRS.h.
const OpticalFlow* AP_AHRS::get_optflow () const inline
Definition at line 175 of file AP_AHRS.h.
virtual bool AP_AHRS::get_position (struct Location & loc) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_Frsky_Telem::calc_home(), AP_Frsky_Telem::calc_nav_alt(), AP_Avoidance::check_for_threats(), AP_Mission::get_landing_sequence_start(), AP_AHRS_View::get_position(), get_rotation_vehicle_body_to_autopilot_body(), AP_Avoidance::get_vector_perpendicular(), SoaringController::init_thermalling(), DataFlash_Class::Log_Write_POS(), AP_ADSB::update(), AP_L1_Control::update_loiter(), AP_Landing_Deepstall::update_steering(), SoaringController::update_thermalling(), and AP_L1_Control::update_waypoint().
virtual uint8_t AP_AHRS::get_primary_accel_index (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 217 of file AP_AHRS.h.
Referenced by AC_PrecLand::construct_pos_meas_using_rangefinder(), and AC_PrecLand::run_output_prediction().
virtual uint8_t AP_AHRS::get_primary_gyro_index (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 222 of file AP_AHRS.h.
Referenced by get_gyro_latest().
virtual void AP_AHRS::get_relative_position_D_home (float & posD) const pure virtual
Implemented in AP_AHRS_NavEKF, and AP_AHRS_DCM.
Referenced by SoaringController::get_altitude_wrt_home(), AP_AHRS_View::get_relative_position_D_home(), get_relative_position_NE_origin(), DataFlash_Class::Log_Write_POS(), AP_Landing_Deepstall::request_go_around(), Variometer::update(), AP_TECS::update_50hz(), and AP_Landing_Deepstall::verify_land().
virtual bool AP_AHRS::get_relative_position_D_origin (float & posD) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 386 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_relative_position_D_origin(), and DataFlash_Class::Log_Write_POS().
virtual bool AP_AHRS::get_relative_position_NE_home (Vector2f & vecNE) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 370 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_relative_position_NE_home().
virtual bool AP_AHRS::get_relative_position_NE_origin (Vector2f & vecNE) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 376 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_relative_position_NE_origin().
virtual bool AP_AHRS::get_relative_position_NED_home (Vector3f & vec) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 358 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_relative_position_NED_home(), GCS_MAVLINK::send_local_position(), and AC_PrecLand_SITL::update().
virtual bool AP_AHRS::get_relative_position_NED_origin (Vector3f & vec) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 365 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_relative_position_NED_origin(), and AP_ICEngine::update().
const Matrix3f& AP_AHRS::get_rotation_autopilot_body_to_vehicle_body (void) const inline
Definition at line 297 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_SITL().
virtual const Matrix3f& AP_AHRS::get_rotation_body_to_ned (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), get_yaw_rate_earth(), AC_PrecLand::run_output_prediction(), AC_PrecLand_SITL::update(), AP_AHRS_View::update(), AC_PrecLand::update(), AP_TECS::update_50hz(), update_AOA_SSA(), and update_trig().
const Matrix3f& AP_AHRS::get_rotation_vehicle_body_to_autopilot_body (void) const inline
Definition at line 298 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::euler_angles(), NavEKF2_core::getRotationBodyToNED(), and NavEKF3_core::getRotationBodyToNED().
virtual bool AP_AHRS::get_secondary_attitude (Vector3f & eulers) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 451 of file AP_AHRS.h.
Referenced by DataFlash_Class::Log_Write_AHRS2(), and GCS_MAVLINK::send_ahrs2().
virtual bool AP_AHRS::get_secondary_position (struct Location & loc) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 461 of file AP_AHRS.h.
Referenced by DataFlash_Class::Log_Write_AHRS2().
virtual bool AP_AHRS::get_secondary_quaternion (Quaternion & quat) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 456 of file AP_AHRS.h.
Referenced by DataFlash_Class::Log_Write_AHRS2().
uint32_t AP_AHRS::get_time_flying_ms (void) const inline
Definition at line 143 of file AP_AHRS.h.
Referenced by NavEKF2_core::detectFlight(), and NavEKF3_core::detectFlight().
const Vector3f& AP_AHRS::get_trim () const inline
Definition at line 417 of file AP_AHRS.h.
Referenced by NavEKF2_core::getEulerAngles(), and NavEKF3_core::getEulerAngles().
virtual bool AP_AHRS::get_variances (float & velVar, float & posVar, float & hgtVar, Vector3f & magVar, float & tasVar, Vector2f & offset) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 537 of file AP_AHRS.h.
Referenced by AP_Frsky_Telem::check_ekf_status().
AHRS_VehicleClass AP_AHRS::get_vehicle_class (void) const inline
Definition at line 150 of file AP_AHRS.h.
Referenced by NavEKF2_core::assume_zero_sideslip(), and NavEKF3_core::assume_zero_sideslip().
virtual bool AP_AHRS::get_velocity_NED (Vector3f & vec) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 341 of file AP_AHRS.h.
Referenced by AP_Frsky_Telem::calc_velandyaw(), AP_Avoidance::check_for_threats(), AP_AHRS_View::get_velocity_NED(), GCS_MAVLINK::send_local_position(), AP_TECS::update_50hz(), and update_AOA_SSA().
float AP_AHRS::get_yaw_rate_earth (void) const inline
Definition at line 240 of file AP_AHRS.h.
Referenced by AP_SteerController::get_steering_out_rate().
float AP_AHRS::getAOA (void)
Definition at line 390 of file AP_AHRS.cpp.
Referenced by getCorrectedDeltaVelocityNED(), and DataFlash_Class::Log_Write_AOA_SSA().
virtual void AP_AHRS::getCorrectedDeltaVelocityNED (Vector3f & ret, float & dt) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 550 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), and AC_PrecLand::update().
virtual uint32_t AP_AHRS::getLastPosDownReset (float & posDelta) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 520 of file AP_AHRS.h.
Referenced by AP_AHRS_View::getLastPosDownReset().
virtual uint32_t AP_AHRS::getLastPosNorthEastReset (Vector2f & pos) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 508 of file AP_AHRS.h.
Referenced by AP_AHRS_View::getLastPosNorthEastReset().
virtual uint32_t AP_AHRS::getLastVelNorthEastReset (Vector2f & vel) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 514 of file AP_AHRS.h.
virtual uint32_t AP_AHRS::getLastYawResetAngle (float & yawAng) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 502 of file AP_AHRS.h.
float AP_AHRS::getSSA (void)
Definition at line 397 of file AP_AHRS.cpp.
Referenced by getCorrectedDeltaVelocityNED(), and DataFlash_Class::Log_Write_AOA_SSA().
float AP_AHRS::groundspeed (void) inline
Definition at line 391 of file AP_AHRS.h.
Referenced by AP_Frsky_Telem::calc_velandyaw(), AP_SteerController::get_steering_out_lat_accel(), AP_SteerController::get_steering_out_rate(), AP_AHRS_View::groundspeed(), and AP_Landing::type_slope_setup_landing_glide_slope().
Vector2f AP_AHRS::groundspeed_vector (void) virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 189 of file AP_AHRS.cpp.
Referenced by airspeed_sensor_enabled(), groundspeed(), AP_AHRS_View::groundspeed_vector(), AP_AHRS_NavEKF::groundspeed_vector(), AP_L1_Control::update_heading_hold(), AP_L1_Control::update_loiter(), AP_L1_Control::update_waypoint(), AP_Landing_Deepstall::verify_breakout(), and AP_Landing_Deepstall::verify_land().
virtual bool AP_AHRS::have_ekf_logging (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 253 of file AP_AHRS.h.
virtual bool AP_AHRS::have_inertial_nav (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 483 of file AP_AHRS.h.
virtual bool AP_AHRS::healthy (void) const pure virtual
Implemented in AP_AHRS_NavEKF, and AP_AHRS_DCM.
Referenced by get_active_accel_instance().
virtual void AP_AHRS::init (void) inline virtual
Definition at line 105 of file AP_AHRS.h.
Referenced by setup().
virtual bool AP_AHRS::initialised (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 496 of file AP_AHRS.h.
virtual const char* AP_AHRS::prearm_failure_reason (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 248 of file AP_AHRS.h.
virtual void AP_AHRS::reset (bool recover_eulers = false) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
virtual void AP_AHRS::reset_attitude (const float & roll, const float & pitch, const float & yaw) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
virtual void AP_AHRS::reset_gyro_drift (void) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
virtual bool AP_AHRS::resetHeightDatum (void) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 529 of file AP_AHRS.h.
void AP_AHRS::set_airspeed (AP_Airspeed * airspeed) inline
Definition at line 188 of file AP_AHRS.h.
void AP_AHRS::set_beacon (AP_Beacon * beacon) inline
Definition at line 192 of file AP_AHRS.h.
void AP_AHRS::set_compass (Compass * compass) inline
Definition at line 162 of file AP_AHRS.h.
Referenced by setup().
void AP_AHRS::set_correct_centrifugal (bool setting) inline
Definition at line 407 of file AP_AHRS.h.
void AP_AHRS::set_fly_forward (bool b) inline
Definition at line 110 of file AP_AHRS.h.
virtual void AP_AHRS::set_home (const Location & loc) pure virtual
Implemented in AP_AHRS_NavEKF, and AP_AHRS_DCM.
Referenced by get_home().
void AP_AHRS::set_likely_flying (bool b) inline
Definition at line 123 of file AP_AHRS.h.
void AP_AHRS::set_optflow (const OpticalFlow * optflow) inline
Definition at line 171 of file AP_AHRS.h.
void AP_AHRS::set_orientation () inline
Definition at line 181 of file AP_AHRS.h.
Referenced by init(), and set_compass().
virtual bool AP_AHRS::set_origin (const Location & loc) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 479 of file AP_AHRS.h.
void AP_AHRS::set_trim (Vector3f new_trim) virtual
Definition at line 162 of file AP_AHRS.cpp.
Referenced by get_trim().
void AP_AHRS::set_vehicle_class (AHRS_VehicleClass vclass) inline
Definition at line 154 of file AP_AHRS.h.
void AP_AHRS::set_wind_estimation (bool b) inline
Definition at line 158 of file AP_AHRS.h.
float AP_AHRS::sin_pitch () const inline
Definition at line 440 of file AP_AHRS.h.
float AP_AHRS::sin_roll () const inline
Definition at line 437 of file AP_AHRS.h.
float AP_AHRS::sin_yaw () const inline
Definition at line 443 of file AP_AHRS.h.
Referenced by AC_Avoid::adjust_velocity_polygon().
virtual void AP_AHRS::update (bool skip_ins_update = false) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by get_yaw_rate_earth().
void AP_AHRS::update_AOA_SSA (void) virtual
Definition at line 343 of file AP_AHRS.cpp.
Referenced by getAOA(), getCorrectedDeltaVelocityNED(), getSSA(), and AP_AHRS_DCM::update().
void AP_AHRS::update_cd_values (void) protected
Definition at line 308 of file AP_AHRS.cpp.
Referenced by AP_AHRS_DCM::euler_angles(), AP_AHRS_NavEKF::update_DCM(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_AHRS_NavEKF::update_SITL().
void AP_AHRS::update_trig (void) protected
Definition at line 292 of file AP_AHRS.cpp.
Referenced by AP_AHRS_DCM::update(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_AHRS_NavEKF::update_SITL().
virtual uint32_t AP_AHRS::uptime_ms (void) const pure virtual
Implemented in AP_AHRS_DCM.
Referenced by get_variances().
virtual bool AP_AHRS::use_compass (void) inline virtual
Reimplemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Definition at line 396 of file AP_AHRS.h.
virtual Vector3f AP_AHRS::wind_estimate (void) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_Landing_Deepstall::build_approach_path(), get_rotation_vehicle_body_to_autopilot_body(), groundspeed_vector(), AP_Landing::head_wind(), update_AOA_SSA(), SoaringController::update_thermalling(), AP_Landing_Deepstall::verify_land(), AP_Landing::wind_alignment(), and AP_AHRS_View::wind_estimate().
bool AP_AHRS::yaw_initialised (void) const inline
Definition at line 401 of file AP_AHRS.h.
Friends And Related Function Documentation
friend class AP_AHRS_View friend
Definition at line 53 of file AP_AHRS.h.
Referenced by create_view().
Member Data Documentation
Vector3f AP_AHRS::_accel_ef[INS_MAX_INSTANCES] protected
Definition at line 638 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::_yaw_gain(), AP_AHRS_DCM::drift_correction(), and get_accel_ef().
Vector3f AP_AHRS::_accel_ef_blended protected
Definition at line 639 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction(), and get_accel_ef_blended().
uint8_t AP_AHRS::_active_accel_instance protected
Definition at line 655 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::_yaw_gain(), AP_AHRS_DCM::drift_correction(), and get_active_accel_instance().
AP_Airspeed* AP_AHRS::_airspeed protected
Definition at line 611 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::airspeed_estimate(), airspeed_estimate(), airspeed_sensor_enabled(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), get_airspeed(), get_EAS2TAS(), and set_airspeed().
float AP_AHRS::_AOA protected
Definition at line 661 of file AP_AHRS.h.
Referenced by getAOA(), and update_AOA_SSA().
AP_Baro& AP_AHRS::_baro protected
Definition at line 622 of file AP_AHRS.h.
Referenced by get_baro(), AP_AHRS_DCM::get_position(), AP_AHRS_DCM::get_relative_position_D_home(), and AP_AHRS_NavEKF::get_relative_position_D_home().
AP_Beacon* AP_AHRS::_beacon protected
Definition at line 614 of file AP_AHRS.h.
Referenced by get_beacon(), and set_beacon().
AP_Int8 AP_AHRS::_board_orientation protected
Definition at line 575 of file AP_AHRS.h.
Referenced by set_orientation().
Compass* AP_AHRS::_compass protected
Definition at line 605 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_AHRS_DCM::drift_correction_yaw(), get_compass(), set_compass(), set_orientation(), AP_AHRS_DCM::use_compass(), use_compass(), and AP_AHRS_DCM::yaw_error_compass().
uint32_t AP_AHRS::_compass_last_update protected
Definition at line 617 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction_yaw().
float AP_AHRS::_cos_pitch protected
Definition at line 651 of file AP_AHRS.h.
Referenced by cos_pitch(), and update_trig().
float AP_AHRS::_cos_roll protected
Definition at line 651 of file AP_AHRS.h.
Referenced by cos_roll(), and update_trig().
float AP_AHRS::_cos_yaw protected
Definition at line 651 of file AP_AHRS.h.
Referenced by cos_yaw(), and update_trig().
AP_Int8 AP_AHRS::_ekf_type protected
Definition at line 578 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::ekf_type(), get_ekf_type(), AP_AHRS_NavEKF::set_ekf_use(), and AP_AHRS_NavEKF::update().
struct AP_AHRS::ahrs_flags AP_AHRS::_flags protected
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_AHRS_DCM::airspeed_estimate(), AP_AHRS(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::estimate_wind(), get_correct_centrifugal(), get_fly_forward(), get_likely_flying(), AP_AHRS_DCM::get_position(), get_time_flying_ms(), set_correct_centrifugal(), set_fly_forward(), set_likely_flying(), set_wind_estimation(), AP_AHRS_DCM::use_compass(), and yaw_initialised().
const AP_GPS& AP_AHRS::_gps protected
Definition at line 623 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_AHRS_DCM::airspeed_estimate(), airspeed_estimate(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::drift_correction_yaw(), get_gps(), AP_AHRS_DCM::get_position(), groundspeed_vector(), AP_AHRS_DCM::have_gps(), and AP_AHRS_DCM::use_compass().
AP_Int8 AP_AHRS::_gps_delay protected
Definition at line 577 of file AP_AHRS.h.
AP_Int8 AP_AHRS::_gps_minsats protected
Definition at line 576 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction().
AP_Int8 AP_AHRS::_gps_use protected
Definition at line 573 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::have_gps().
float AP_AHRS::_gyro_drift_limit protected
Definition at line 635 of file AP_AHRS.h.
Referenced by AP_AHRS(), and AP_AHRS_DCM::drift_correction().
struct Location AP_AHRS::_home protected
Definition at line 648 of file AP_AHRS.h.
Referenced by AP_AHRS(), get_home(), AP_AHRS_DCM::get_position(), AP_AHRS_NavEKF::get_relative_position_D_home(), AP_AHRS_NavEKF::get_relative_position_NE_home(), AP_AHRS_NavEKF::get_relative_position_NED_home(), and AP_AHRS_DCM::set_home().
Vector2f AP_AHRS::_hp protected
Definition at line 644 of file AP_AHRS.h.
Referenced by groundspeed_vector().
AP_InertialSensor& AP_AHRS::_ins protected
Definition at line 621 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction(), get_accel_ef(), get_ins(), get_primary_accel_index(), AP_AHRS_NavEKF::get_primary_accel_index(), get_primary_gyro_index(), AP_AHRS_NavEKF::get_primary_gyro_index(), AP_AHRS_NavEKF::get_primary_IMU_index(), AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), getCorrectedDeltaVelocityNED(), AP_AHRS_DCM::matrix_update(), AP_AHRS_DCM::reset(), set_orientation(), AP_AHRS_DCM::update(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_EKF3().
AP_Float AP_AHRS::_kp protected
Definition at line 569 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction().
AP_Float AP_AHRS::_kp_yaw protected
Definition at line 568 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction_yaw().
uint32_t AP_AHRS::_last_AOA_update_ms protected
Definition at line 662 of file AP_AHRS.h.
Referenced by update_AOA_SSA().
uint32_t AP_AHRS::_last_flying_ms protected
Definition at line 590 of file AP_AHRS.h.
Referenced by get_time_flying_ms(), and set_likely_flying().
Vector3f AP_AHRS::_last_trim protected
Definition at line 629 of file AP_AHRS.h.
Referenced by AP_AHRS(), and update_trig().
Vector2f AP_AHRS::_lastGndVelADS protected
Definition at line 645 of file AP_AHRS.h.
Referenced by groundspeed_vector().
Vector2f AP_AHRS::_lp protected
Definition at line 643 of file AP_AHRS.h.
Referenced by groundspeed_vector().
const OpticalFlow* AP_AHRS::_optflow protected
Definition at line 608 of file AP_AHRS.h.
Referenced by get_optflow(), and set_optflow().
Matrix3f AP_AHRS::_rotation_autopilot_body_to_vehicle_body protected
Definition at line 630 of file AP_AHRS.h.
Referenced by AP_AHRS(), get_rotation_autopilot_body_to_vehicle_body(), and update_trig().
Matrix3f AP_AHRS::_rotation_vehicle_body_to_autopilot_body protected
Definition at line 631 of file AP_AHRS.h.
Referenced by AP_AHRS(), get_rotation_vehicle_body_to_autopilot_body(), and update_trig().
float AP_AHRS::_sin_pitch protected
Definition at line 652 of file AP_AHRS.h.
Referenced by sin_pitch(), and update_trig().
float AP_AHRS::_sin_roll protected
Definition at line 652 of file AP_AHRS.h.
Referenced by sin_roll(), and update_trig().
float AP_AHRS::_sin_yaw protected
Definition at line 652 of file AP_AHRS.h.
Referenced by sin_yaw(), and update_trig().
float AP_AHRS::_SSA protected
Definition at line 661 of file AP_AHRS.h.
Referenced by getSSA(), and update_AOA_SSA().
AP_Vector3f AP_AHRS::_trim protected
Definition at line 626 of file AP_AHRS.h.
Referenced by add_trim(), AP_AHRS(), get_trim(), set_trim(), and update_trig().
AHRS_VehicleClass AP_AHRS::_vehicle_class protected
Definition at line 564 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), get_vehicle_class(), AP_AHRS_NavEKF::healthy(), and set_vehicle_class().
AP_AHRS_View* AP_AHRS::_view protected
Definition at line 658 of file AP_AHRS.h.
Referenced by create_view(), and AP_AHRS_NavEKF::update().
AP_Int8 AP_AHRS::_wind_max protected
Definition at line 574 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::airspeed_estimate(), and airspeed_estimate().
AP_Float AP_AHRS::beta protected
Definition at line 572 of file AP_AHRS.h.
Referenced by groundspeed_vector().
AP_Float AP_AHRS::gps_gain protected
Definition at line 570 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction().
float AP_AHRS::pitch
Definition at line 259 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_TECS::_initialise_states(), AP_Module::call_hook_AHRS_update(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::euler_angles(), AP_AHRS_DCM::get_gyro_drift(), loop(), AP_L1_Control::nav_roll_cd(), AP_AHRS_NavEKF::reset(), AP_AHRS_DCM::reset(), AP_AHRS_NavEKF::reset_attitude(), update_cd_values(), AP_AHRS_NavEKF::update_DCM(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_AHRS_NavEKF::update_SITL().
int32_t AP_AHRS::pitch_sensor
Definition at line 264 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_PitchController::_get_rate_out(), AP_Frsky_Telem::calc_attiandrng(), AP_AHRS_DCM::drift_correction(), DataFlash_Class::Log_Write_Attitude(), DataFlash_Class::Log_Write_CameraInfo(), AP_Camera::send_feedback(), and update_cd_values().
float AP_AHRS::roll
Definition at line 258 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_Module::call_hook_AHRS_update(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::euler_angles(), AP_AHRS_DCM::get_gyro_drift(), AP_YawController::get_servo_out(), loop(), AP_AHRS_NavEKF::reset(), AP_AHRS_DCM::reset(), AP_AHRS_NavEKF::reset_attitude(), Variometer::update(), update_cd_values(), AP_AHRS_NavEKF::update_DCM(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_AHRS_NavEKF::update_SITL().
int32_t AP_AHRS::roll_sensor
Definition at line 263 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_rate_out(), AP_Frsky_Telem::calc_attiandrng(), DataFlash_Class::Log_Write_Attitude(), DataFlash_Class::Log_Write_CameraInfo(), AP_Camera::send_feedback(), AP_Camera::update(), and update_cd_values().
const AP_Param::GroupInfo AP_AHRS::var_info static
Definition at line 448 of file AP_AHRS.h.
Referenced by AP_AHRS().
float AP_AHRS::yaw
Definition at line 260 of file AP_AHRS.h.
Referenced by AP_Module::call_hook_AHRS_update(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::euler_angles(), AP_AHRS_DCM::get_gyro_drift(), AP_L1_Control::get_yaw(), groundspeed_vector(), SoaringController::init_thermalling(), loop(), AP_AHRS_NavEKF::reset(), AP_AHRS_DCM::reset(), AP_AHRS_NavEKF::reset_attitude(), update_cd_values(), AP_AHRS_NavEKF::update_DCM(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), AP_L1_Control::update_level_flight(), AP_L1_Control::update_loiter(), AP_AHRS_NavEKF::update_SITL(), and AP_Landing_Deepstall::update_steering().
int32_t AP_AHRS::yaw_sensor
Definition at line 265 of file AP_AHRS.h.
Referenced by AP_Frsky_Telem::calc_velandyaw(), AP_L1_Control::get_yaw_sensor(), AP_Landing::head_wind(), DataFlash_Class::Log_Write_Attitude(), DataFlash_Class::Log_Write_CameraInfo(), AP_Frsky_Telem::send_D(), AP_Camera::send_feedback(), AP_Frsky_Telem::send_SPort(), update_cd_values(), AP_L1_Control::update_heading_hold(), AP_L1_Control::update_level_flight(), and AP_AHRS_DCM::use_compass().
The documentation for this class was generated from the following files:
libraries/AP_AHRS/AP_AHRS.h
libraries/AP_AHRS/AP_AHRS.cpp