APM:Libraries: DataFlash_Backend Class Reference
DataFlash_Backend Class Reference abstract
#include <DataFlash_Backend.h>
Public Member Functions
FUNCTOR_TYPEDEF (print_mode_fn, void, AP_HAL::BetterStream *, uint8_t)
FUNCTOR_TYPEDEF (vehicle_startup_message_Log_Writer, void)
DataFlash_Backend (DataFlash_Class &front, class DFMessageWriter_DFLogStart *writer)
vehicle_startup_message_Log_Writer vehicle_message_writer ()
void internal_error ()
virtual bool CardInserted (void) const =0
virtual void EraseAll ()=0
virtual bool NeedPrep ()=0
virtual void Prep ()=0
bool WriteBlock (const void *pBuffer, uint16_t size)
bool WriteCriticalBlock (const void *pBuffer, uint16_t size)
bool WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)
virtual uint16_t find_last_log ()=0
virtual void get_log_boundaries (uint16_t log_num, uint16_t &start_page, uint16_t &end_page)=0
virtual void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)=0
virtual int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)=0
virtual uint16_t get_num_logs ()=0
virtual void LogReadProcess (const uint16_t list_entry, uint16_t start_page, uint16_t end_page, print_mode_fn printMode, AP_HAL::BetterStream *port)=0
virtual void DumpPageInfo (AP_HAL::BetterStream *port)=0
virtual void ShowDeviceInfo (AP_HAL::BetterStream *port)=0
virtual void ListAvailableLogs (AP_HAL::BetterStream *port)=0
virtual bool logging_started (void) const =0
virtual void Init ()
void set_mission (const AP_Mission *mission)
virtual uint32_t bufferspace_available ()=0
virtual void PrepForArming ()
virtual uint16_t start_new_log (void)=0
virtual void stop_logging (void)=0
void Log_Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
virtual void flush (void)
virtual void remote_log_block_status_msg (mavlink_channel_t chan, mavlink_message_t *msg)
virtual void periodic_tasks ()
uint8_t num_types () const
const struct LogStructure * structure (uint8_t structure) const
void Log_Write_EntireMission (const AP_Mission &mission)
bool Log_Write_Format (const struct LogStructure *structure)
bool Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t &mav_cmd)
bool Log_Write_Message (const char *message)
bool Log_Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
bool Log_Write_Mode (uint8_t mode, uint8_t reason=0)
bool Log_Write_Parameter (const char *name, float value)
bool Log_Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type)
uint32_t num_dropped (void) const
bool Log_Write_Emit_FMT (uint8_t msg_type)
bool Log_Write (uint8_t msg_type, va_list arg_list, bool is_critical=false)
virtual bool logging_enabled () const =0
virtual bool logging_failed () const =0
virtual void vehicle_was_disarmed ()
Protected Member Functions
virtual void periodic_10Hz (const uint32_t now)
virtual void periodic_1Hz (const uint32_t now)
virtual void periodic_fullrate (const uint32_t now)
void _print_log_entry (uint8_t msg_type, print_mode_fn print_mode, AP_HAL::BetterStream *port)
bool ShouldLog () const
virtual bool WritesOK () const =0
virtual bool StartNewLogOK () const
virtual bool ReadBlock (void *pkt, uint16_t size)=0
virtual bool WriteBlockCheckStartupMessages ()
virtual void WriteMoreStartupMessages ()
virtual void push_log_blocks ()
virtual void start_new_log_reset_variables ()
virtual bool _WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)=0
Protected Attributes
uint32_t dropped
uint8_t internal_errors
DataFlash_Class & _front
DFMessageWriter_DFLogStart * _startup_messagewriter
bool _writing_startup_messages
uint32_t _internal_errors
uint32_t _dropped
bool _initialised
Private Attributes
uint32_t _last_periodic_1Hz
uint32_t _last_periodic_10Hz
Detailed Description
Definition at line 7 of file DataFlash_Backend.h.
Constructor & Destructor Documentation
DataFlash_Backend::DataFlash_Backend (DataFlash_Class & front, class DFMessageWriter_DFLogStart * writer)
Definition at line 7 of file DataFlash_Backend.cpp.
Member Function Documentation
void DataFlash_Backend::_print_log_entry (uint8_t msg_type, print_mode_fn print_mode, AP_HAL::BetterStream * port) protected
Definition at line 25 of file LogFile.cpp.
virtual bool DataFlash_Backend::_WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical) protected pure virtual
Implemented in DataFlash_MAVLink.
Referenced by WritePrioritisedBlock().
virtual uint32_t DataFlash_Backend::bufferspace_available () pure virtual
Implemented in DataFlash_MAVLink.
Referenced by Init(), Log_Write(), and DFMessageWriter_DFLogStart::process().
virtual bool DataFlash_Backend::CardInserted (void) const pure virtual
Implemented in DataFlash_MAVLink.
virtual void DataFlash_Backend::DumpPageInfo (AP_HAL::BetterStream * port) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::DumpPageInfo(), and WriteCriticalBlock().
virtual void DataFlash_Backend::EraseAll () pure virtual
Implemented in DataFlash_MAVLink.
virtual uint16_t DataFlash_Backend::find_last_log () pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::find_last_log(), and WriteCriticalBlock().
virtual void DataFlash_Backend::flush (void) inline virtual
Definition at line 78 of file DataFlash_Backend.h.
DataFlash_Backend::FUNCTOR_TYPEDEF (print_mode_fn , void , AP_HAL::BetterStream * , uint8_t)
DataFlash_Backend::FUNCTOR_TYPEDEF (vehicle_startup_message_Log_Writer , void)
virtual void DataFlash_Backend::get_log_boundaries (uint16_t log_num, uint16_t & start_page, uint16_t & end_page) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::get_log_boundaries(), and WriteCriticalBlock().
virtual int16_t DataFlash_Backend::get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::get_log_data(), and WriteCriticalBlock().
virtual void DataFlash_Backend::get_log_info (uint16_t log_num, uint32_t & size, uint32_t & time_utc) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::get_log_info(), and WriteCriticalBlock().
virtual uint16_t DataFlash_Backend::get_num_logs () pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::get_num_logs(), and WriteCriticalBlock().
virtual void DataFlash_Backend::Init () inline virtual
Reimplemented in DataFlash_MAVLink.
Definition at line 56 of file DataFlash_Backend.h.
Referenced by DataFlash_MAVLink::Init(), and DataFlash_Class::Init().
void DataFlash_Backend::internal_error ()
Definition at line 59 of file DataFlash_Backend.cpp.
Referenced by DataFlash_MAVLink::internal_error(), Log_Write(), and Log_Write_Emit_FMT().
virtual void DataFlash_Backend::ListAvailableLogs (AP_HAL::BetterStream * port) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::ListAvailableLogs(), and WriteCriticalBlock().
void DataFlash_Backend::Log_Fill_Format (const struct LogStructure * structure, struct log_Format & pkt)
Definition at line 196 of file LogFile.cpp.
Referenced by Log_Write_Format(), and PrepForArming().
bool DataFlash_Backend::Log_Write (uint8_t msg_type, va_list arg_list, bool is_critical = false)
Definition at line 146 of file DataFlash_Backend.cpp.
Referenced by DataFlash_Class::Log_Write(), DataFlash_Class::Log_Write_POS(), and num_dropped().
bool DataFlash_Backend::Log_Write_Emit_FMT (uint8_t msg_type)
Definition at line 120 of file DataFlash_Backend.cpp.
Referenced by num_dropped().
void DataFlash_Backend::Log_Write_EntireMission (const AP_Mission & mission)
Definition at line 600 of file LogFile.cpp.
Referenced by remote_log_block_status_msg().
bool DataFlash_Backend::Log_Write_Format (const struct LogStructure * structure)
Definition at line 212 of file LogFile.cpp.
Referenced by Log_Write_Emit_FMT(), DFMessageWriter_DFLogStart::process(), and remote_log_block_status_msg().
bool DataFlash_Backend::Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t & mav_cmd)
Definition at line 1456 of file LogFile.cpp.
Referenced by Log_Write_Mission_Cmd(), and remote_log_block_status_msg().
bool DataFlash_Backend::Log_Write_Message (const char * message)
Definition at line 609 of file LogFile.cpp.
Referenced by DFMessageWriter_WriteSysInfo::process(), DFMessageWriter_WriteEntireMission::process(), and remote_log_block_status_msg().
bool DataFlash_Backend::Log_Write_Mission_Cmd (const AP_Mission & mission, const AP_Mission::Mission_Command & cmd)
Definition at line 592 of file LogFile.cpp.
Referenced by DFMessageWriter_WriteEntireMission::process(), and remote_log_block_status_msg().
bool DataFlash_Backend::Log_Write_Mode (uint8_t mode, uint8_t reason = 0)
Definition at line 1713 of file LogFile.cpp.
Referenced by remote_log_block_status_msg().
bool DataFlash_Backend::Log_Write_Parameter (const char * name, float value)
Definition at line 222 of file LogFile.cpp.
Referenced by Log_Write_Parameter(), DFMessageWriter_DFLogStart::process(), and remote_log_block_status_msg().
bool DataFlash_Backend::Log_Write_Parameter (const AP_Param * ap, const AP_Param::ParamToken & token, enum ap_var_type type)
Definition at line 237 of file LogFile.cpp.
virtual bool DataFlash_Backend::logging_enabled () const pure virtual
Implemented in DataFlash_MAVLink.
Referenced by num_dropped().
virtual bool DataFlash_Backend::logging_failed () const pure virtual
Implemented in DataFlash_MAVLink.
Referenced by num_dropped().
virtual bool DataFlash_Backend::logging_started (void) const pure virtual
Implemented in DataFlash_MAVLink.
Referenced by StartNewLogOK(), and WriteCriticalBlock().
virtual void DataFlash_Backend::LogReadProcess (const uint16_t list_entry, uint16_t start_page, uint16_t end_page, print_mode_fn printMode, AP_HAL::BetterStream * port) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::LogReadProcess(), and WriteCriticalBlock().
virtual bool DataFlash_Backend::NeedPrep () pure virtual
Implemented in DataFlash_MAVLink.
uint32_t DataFlash_Backend::num_dropped (void) const inline
Definition at line 103 of file DataFlash_Backend.h.
Referenced by DataFlash_Class::num_dropped().
uint8_t DataFlash_Backend::num_types () const
Definition at line 15 of file DataFlash_Backend.cpp.
Referenced by _print_log_entry(), DataFlash_Class::instance(), and remote_log_block_status_msg().
void DataFlash_Backend::periodic_10Hz (const uint32_t now) protected virtual
Reimplemented in DataFlash_MAVLink.
Definition at line 29 of file DataFlash_Backend.cpp.
Referenced by periodic_tasks().
void DataFlash_Backend::periodic_1Hz (const uint32_t now) protected virtual
Reimplemented in DataFlash_MAVLink.
Definition at line 32 of file DataFlash_Backend.cpp.
Referenced by periodic_tasks().
void DataFlash_Backend::periodic_fullrate (const uint32_t now) protected virtual
Reimplemented in DataFlash_MAVLink.
Definition at line 35 of file DataFlash_Backend.cpp.
Referenced by periodic_tasks().
void DataFlash_Backend::periodic_tasks () virtual
Definition at line 39 of file DataFlash_Backend.cpp.
Referenced by remote_log_block_status_msg().
virtual void DataFlash_Backend::Prep () pure virtual
Implemented in DataFlash_MAVLink.
virtual void DataFlash_Backend::PrepForArming () inline virtual
Definition at line 62 of file DataFlash_Backend.h.
void DataFlash_Backend::push_log_blocks () protected virtual
Reimplemented in DataFlash_MAVLink.
Definition at line 72 of file DataFlash_Backend.cpp.
Referenced by WriteBlockCheckStartupMessages().
virtual bool DataFlash_Backend::ReadBlock (void * pkt, uint16_t size) protected pure virtual
Implemented in DataFlash_MAVLink.
Referenced by _print_log_entry().
virtual void DataFlash_Backend::remote_log_block_status_msg (mavlink_channel_t chan, mavlink_message_t * msg) inline virtual
Reimplemented in DataFlash_MAVLink.
Definition at line 82 of file DataFlash_Backend.h.
void DataFlash_Backend::set_mission (const AP_Mission * mission)
Definition at line 66 of file DataFlash_Backend.cpp.
Referenced by Init().
bool DataFlash_Backend::ShouldLog () const protected
Definition at line 291 of file DataFlash_Backend.cpp.
Referenced by WritePrioritisedBlock().
virtual void DataFlash_Backend::ShowDeviceInfo (AP_HAL::BetterStream * port) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by DataFlash_Class::ShowDeviceInfo(), and WriteCriticalBlock().
virtual uint16_t DataFlash_Backend::start_new_log (void) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by PrepForArming(), and WritePrioritisedBlock().
void DataFlash_Backend::start_new_log_reset_variables () protected virtual
Definition at line 53 of file DataFlash_Backend.cpp.
Referenced by DataFlash_MAVLink::handle_ack().
bool DataFlash_Backend::StartNewLogOK () const protected virtual
Definition at line 263 of file DataFlash_Backend.cpp.
Referenced by WritePrioritisedBlock().
virtual void DataFlash_Backend::stop_logging (void) pure virtual
Implemented in DataFlash_MAVLink.
Referenced by PrepForArming().
const struct LogStructure * DataFlash_Backend::structure (uint8_t structure) const
Definition at line 20 of file DataFlash_Backend.cpp.
Referenced by _print_log_entry(), PrepForArming(), DFMessageWriter_DFLogStart::process(), and remote_log_block_status_msg().
DataFlash_Backend::vehicle_startup_message_Log_Writer DataFlash_Backend::vehicle_message_writer ()
Definition at line 25 of file DataFlash_Backend.cpp.
Referenced by DFMessageWriter_DFLogStart::process().
virtual void DataFlash_Backend::vehicle_was_disarmed () inline virtual
Definition at line 122 of file DataFlash_Backend.h.
bool DataFlash_Backend::WriteBlock (const void * pBuffer, uint16_t size) inline
Definition at line 30 of file DataFlash_Backend.h.
Referenced by DataFlash_Class::Log_Write_AHRS2(), DataFlash_Class::Log_Write_Airspeed(), DataFlash_Class::Log_Write_AOA_SSA(), DataFlash_Class::Log_Write_Attitude(), DataFlash_Class::Log_Write_AttitudeView(), DataFlash_Class::Log_Write_Baro(), DataFlash_Class::Log_Write_Beacon(), DataFlash_Class::Log_Write_Compass(), DataFlash_Class::Log_Write_Current(), DataFlash_MAVLink::Log_Write_DF_MAV(), DataFlash_Class::Log_Write_ESC(), DataFlash_Class::Log_Write_GPS(), DataFlash_Class::Log_Write_IMU(), DataFlash_Class::Log_Write_IMUDT(), Log_Write_MavCmd(), DataFlash_Class::Log_Write_Origin(), DataFlash_Class::Log_Write_PID(), DataFlash_Class::Log_Write_POS(), DataFlash_Class::Log_Write_Power(), DataFlash_Class::Log_Write_Proximity(), DataFlash_Class::Log_Write_Radio(), DataFlash_Class::Log_Write_Rally(), DataFlash_Class::Log_Write_Rate(), DataFlash_Class::Log_Write_RCIN(), DataFlash_Class::Log_Write_RCOUT(), DataFlash_Class::Log_Write_RFND(), DataFlash_Class::Log_Write_RPM(), DataFlash_Class::Log_Write_RSSI(), DataFlash_Class::Log_Write_Vibration(), and DataFlash_Class::Log_Write_VisualOdom().
bool DataFlash_Backend::WriteBlockCheckStartupMessages () protected virtual
Definition at line 78 of file DataFlash_Backend.cpp.
Referenced by DataFlash_MAVLink::_WritePrioritisedBlock().
bool DataFlash_Backend::WriteCriticalBlock (const void * pBuffer, uint16_t size) inline
Definition at line 34 of file DataFlash_Backend.h.
Referenced by DataFlash_Class::Log_Write_CameraInfo(), Log_Write_Format(), Log_Write_Message(), Log_Write_Mode(), and Log_Write_Parameter().
void DataFlash_Backend::WriteMoreStartupMessages () protected virtual
Definition at line 103 of file DataFlash_Backend.cpp.
Referenced by DataFlash_MAVLink::push_log_blocks(), and push_log_blocks().
bool DataFlash_Backend::WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical)
Definition at line 277 of file DataFlash_Backend.cpp.
Referenced by Log_Write(), WriteBlock(), and WriteCriticalBlock().
virtual bool DataFlash_Backend::WritesOK () const protected pure virtual
Implemented in DataFlash_MAVLink.
Referenced by WritePrioritisedBlock().
Member Data Documentation
uint32_t DataFlash_Backend::_dropped protected
Definition at line 158 of file DataFlash_Backend.h.
Referenced by num_dropped().
DataFlash_Class& DataFlash_Backend::_front protected
Definition at line 128 of file DataFlash_Backend.h.
Referenced by Log_Write(), Log_Write_Emit_FMT(), num_types(), ShouldLog(), start_new_log_reset_variables(), StartNewLogOK(), structure(), and vehicle_message_writer().
bool DataFlash_Backend::_initialised protected
Definition at line 165 of file DataFlash_Backend.h.
Referenced by DataFlash_MAVLink::do_resends(), DataFlash_MAVLink::handle_ack(), DataFlash_MAVLink::handle_retry(), DataFlash_MAVLink::Init(), DataFlash_MAVLink::push_log_blocks(), DataFlash_MAVLink::send_log_block(), ShouldLog(), DataFlash_MAVLink::stats_collect(), and DataFlash_MAVLink::stats_log().
uint32_t DataFlash_Backend::_internal_errors protected
Definition at line 157 of file DataFlash_Backend.h.
Referenced by internal_error().
uint32_t DataFlash_Backend::_last_periodic_10Hz private
Definition at line 170 of file DataFlash_Backend.h.
Referenced by periodic_tasks().
uint32_t DataFlash_Backend::_last_periodic_1Hz private
Definition at line 169 of file DataFlash_Backend.h.
Referenced by periodic_tasks().
DFMessageWriter_DFLogStart* DataFlash_Backend::_startup_messagewriter protected
Definition at line 154 of file DataFlash_Backend.h.
Referenced by DataFlash_MAVLink::_WritePrioritisedBlock(), set_mission(), start_new_log_reset_variables(), WriteBlockCheckStartupMessages(), and WriteMoreStartupMessages().
bool DataFlash_Backend::_writing_startup_messages protected
Definition at line 155 of file DataFlash_Backend.h.
Referenced by WriteBlockCheckStartupMessages(), and WriteMoreStartupMessages().
uint32_t DataFlash_Backend::dropped protected
Definition at line 122 of file DataFlash_Backend.h.
Referenced by DataFlash_MAVLink::_WritePrioritisedBlock(), DataFlash_MAVLink::Log_Write_DF_MAV(), DataFlash_MAVLink::stats_init(), DataFlash_MAVLink::stats_log(), and vehicle_was_disarmed().
uint8_t DataFlash_Backend::internal_errors protected
Definition at line 126 of file DataFlash_Backend.h.
Referenced by DataFlash_MAVLink::internal_error(), DataFlash_MAVLink::Log_Write_DF_MAV(), DataFlash_MAVLink::stats_init(), and DataFlash_MAVLink::stats_log().
The documentation for this class was generated from the following files:
libraries/DataFlash/DataFlash_Backend.h
libraries/DataFlash/DataFlash_Backend.cpp
libraries/DataFlash/LogFile.cpp