APM:Libraries: AP_BattMonitor Class Reference
AP_BattMonitor Class Reference
#include <AP_BattMonitor.h>
Classes
struct BattMonitor_State
struct cells
Public Types
enum BattMonitor_Type {
BattMonitor_TYPE_NONE = 0, BattMonitor_TYPE_ANALOG_VOLTAGE_ONLY = 3, BattMonitor_TYPE_ANALOG_VOLTAGE_AND_CURRENT = 4, BattMonitor_TYPE_SOLO = 5,
BattMonitor_TYPE_BEBOP = 6, BattMonitor_TYPE_MAXELL = 7
}
enum BattMonitor_LowVoltage_Source { BattMonitor_LowVoltageSource_Raw = 0, BattMonitor_LowVoltageSource_SagCompensated = 1 }
Public Member Functions
AP_BattMonitor ()
Constructor.
uint8_t num_instances (void) const
void init ()
void read ()
Read the battery voltage and current for all batteries. Should be called at 10hz.
bool healthy (uint8_t instance) const
bool healthy () const
bool is_powering_off (uint8_t instance) const
bool is_powering_off () const
bool has_current (uint8_t instance) const
has_current - returns true if battery monitor instance provides current info
bool has_current () const
float voltage (uint8_t instance) const
voltage - returns battery voltage in millivolts
float voltage () const
float voltage_resting_estimate (uint8_t instance) const
float voltage_resting_estimate () const
float current_amps (uint8_t instance) const
current_amps - returns the instantaneous current draw in amperes
float current_amps () const
float current_total_mah (uint8_t instance) const
current_total_mah - returns total current drawn since start-up in amp-hours
float current_total_mah () const
virtual uint8_t capacity_remaining_pct (uint8_t instance) const
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
uint8_t capacity_remaining_pct () const
int32_t pack_capacity_mah (uint8_t instance) const
pack_capacity_mah - returns the capacity of the battery pack in mAh when the pack is full
int32_t pack_capacity_mah () const
bool exhausted (uint8_t instance, float low_voltage, float min_capacity_mah)
exhausted - returns true if the battery's voltage remains below the low_voltage for 10 seconds or remaining capacity falls below min_capacity
bool exhausted (float low_voltage, float min_capacity_mah)
enum BattMonitor_Type get_type ()
get_type - returns battery monitor type
enum BattMonitor_Type get_type (uint8_t instance)
void set_monitoring (uint8_t instance, uint8_t mon)
set_monitoring - sets the monitor type (used for example sketch only)
bool get_watt_max ()
bool get_watt_max (uint8_t instance)
bool overpower_detected () const
true when (voltage * current) > watt_max
bool overpower_detected (uint8_t instance) const
bool has_cell_voltages ()
bool has_cell_voltages (const uint8_t instance) const
const cells & get_cell_voltages () const
const cells & get_cell_voltages (const uint8_t instance) const
bool get_temperature (float &temperature) const
bool get_temperature (float &temperature, const uint8_t instance) const
float get_resistance () const
float get_resistance (uint8_t instance) const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Attributes
AP_Int8 _monitoring [AP_BATT_MONITOR_MAX_INSTANCES]
parameters
AP_Int8 _volt_pin [AP_BATT_MONITOR_MAX_INSTANCES]
0=disabled, 3=voltage only, 4=voltage and current
AP_Int8 _curr_pin [AP_BATT_MONITOR_MAX_INSTANCES]
board pin used to measure battery voltage
AP_Float _volt_multiplier [AP_BATT_MONITOR_MAX_INSTANCES]
board pin used to measure battery current
AP_Float _curr_amp_per_volt [AP_BATT_MONITOR_MAX_INSTANCES]
voltage on volt pin multiplied by this to calculate battery voltage
AP_Float _curr_amp_offset [AP_BATT_MONITOR_MAX_INSTANCES]
voltage on current pin multiplied by this to calculate current in amps
AP_Int32 _pack_capacity [AP_BATT_MONITOR_MAX_INSTANCES]
offset voltage that is subtracted from current pin before conversion to amps
AP_Int16 _watt_max [AP_BATT_MONITOR_MAX_INSTANCES]
battery pack capacity less reserve in mAh
AP_Int32 _serial_numbers [AP_BATT_MONITOR_MAX_INSTANCES]
max battery power allowed. Reduce max throttle to reduce current to satisfy this limit
AP_Int8 _low_voltage_timeout
battery serial number, automatically filled in on SMBus batteries
AP_Int8 _low_voltage_source
timeout in seconds before a low voltage event will be triggered
Private Attributes
BattMonitor_State state [AP_BATT_MONITOR_MAX_INSTANCES]
voltage type used for detection of low voltage event
AP_BattMonitor_Backend * drivers [AP_BATT_MONITOR_MAX_INSTANCES]
uint8_t _num_instances
Friends
class AP_BattMonitor_Backend
class AP_BattMonitor_Analog
class AP_BattMonitor_SMBus
class AP_BattMonitor_SMBus_Solo
class AP_BattMonitor_SMBus_Maxell
Detailed Description
Definition at line 31 of file AP_BattMonitor.h.
Member Enumeration Documentation
enum AP_BattMonitor::BattMonitor_LowVoltage_Source
Enumerator
BattMonitor_LowVoltageSource_Raw
BattMonitor_LowVoltageSource_SagCompensated
Definition at line 55 of file AP_BattMonitor.h.
enum AP_BattMonitor::BattMonitor_Type
Enumerator
BattMonitor_TYPE_NONE
BattMonitor_TYPE_ANALOG_VOLTAGE_ONLY
BattMonitor_TYPE_ANALOG_VOLTAGE_AND_CURRENT
BattMonitor_TYPE_SOLO
BattMonitor_TYPE_BEBOP
BattMonitor_TYPE_MAXELL
Definition at line 45 of file AP_BattMonitor.h.
Constructor & Destructor Documentation
AP_BattMonitor::AP_BattMonitor (void)
Constructor.
Definition at line 169 of file AP_BattMonitor.cpp.
Member Function Documentation
uint8_t AP_BattMonitor::capacity_remaining_pct (uint8_t instance) const virtual
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
Definition at line 303 of file AP_BattMonitor.cpp.
Referenced by GCS_MAVLINK::send_battery_status(), AP_Frsky_Telem::send_D(), and AP_Frsky_Telem::send_SPort().
uint8_t AP_BattMonitor::capacity_remaining_pct () const inline
Definition at line 122 of file AP_BattMonitor.h.
Referenced by capacity_remaining_pct(), and current_total_mah().
float AP_BattMonitor::current_amps (uint8_t instance) const
current_amps - returns the instantaneous current draw in amperes
Definition at line 285 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_Telem::calc_batt(), DataFlash_Class::Log_Write_Current(), loop(), GCS_MAVLINK::send_battery2(), GCS_MAVLINK::send_battery_status(), AP_Frsky_Telem::send_D(), and AP_Frsky_Telem::send_SPort().
float AP_BattMonitor::current_amps () const inline
Definition at line 114 of file AP_BattMonitor.h.
Referenced by current_amps(), and voltage_resting_estimate().
float AP_BattMonitor::current_total_mah (uint8_t instance) const
current_total_mah - returns total current drawn since start-up in amp-hours
Definition at line 294 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_Telem::calc_batt(), DataFlash_Class::Log_Write_Current(), loop(), and GCS_MAVLINK::send_battery_status().
float AP_BattMonitor::current_total_mah () const inline
Definition at line 118 of file AP_BattMonitor.h.
Referenced by current_amps(), current_total_mah(), and exhausted().
bool AP_BattMonitor::exhausted (uint8_t instance, float low_voltage, float min_capacity_mah)
exhausted - returns true if the battery's voltage remains below the low_voltage for 10 seconds or remaining capacity falls below min_capacity
exhausted - returns true if the voltage remains below the low_voltage for 10 seconds or remaining capacity falls below min_capacity_mah
Definition at line 323 of file AP_BattMonitor.cpp.
Referenced by pack_capacity_mah().
bool AP_BattMonitor::exhausted (float low_voltage, float min_capacity_mah) inline
Definition at line 130 of file AP_BattMonitor.h.
Referenced by exhausted().
const cells& AP_BattMonitor::get_cell_voltages () const inline
Definition at line 149 of file AP_BattMonitor.h.
Referenced by get_cell_voltages(), DataFlash_Class::Log_Write_Current(), and GCS_MAVLINK::send_battery_status().
const AP_BattMonitor::cells & AP_BattMonitor::get_cell_voltages (const uint8_t instance) const
Definition at line 397 of file AP_BattMonitor.cpp.
float AP_BattMonitor::get_resistance () const inline
Definition at line 157 of file AP_BattMonitor.h.
Referenced by get_resistance(), and DataFlash_Class::Log_Write_Current().
float AP_BattMonitor::get_resistance (uint8_t instance) const inline
Definition at line 158 of file AP_BattMonitor.h.
bool AP_BattMonitor::get_temperature (float & temperature) const inline
Definition at line 153 of file AP_BattMonitor.h.
Referenced by get_temperature(), DataFlash_Class::Log_Write_Current(), and GCS_MAVLINK::send_battery_status().
bool AP_BattMonitor::get_temperature (float & temperature, const uint8_t instance) const
Definition at line 407 of file AP_BattMonitor.cpp.
enum BattMonitor_Type AP_BattMonitor::get_type () inline
get_type - returns battery monitor type
Definition at line 133 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor_Analog::has_current().
enum BattMonitor_Type AP_BattMonitor::get_type (uint8_t instance) inline
Definition at line 134 of file AP_BattMonitor.h.
bool AP_BattMonitor::get_watt_max () inline
Definition at line 139 of file AP_BattMonitor.h.
Referenced by get_watt_max().
bool AP_BattMonitor::get_watt_max (uint8_t instance) inline
Definition at line 140 of file AP_BattMonitor.h.
bool AP_BattMonitor::has_cell_voltages () inline
Definition at line 147 of file AP_BattMonitor.h.
Referenced by has_cell_voltages(), and DataFlash_Class::Log_Write_Current().
bool AP_BattMonitor::has_cell_voltages (const uint8_t instance) const
Definition at line 387 of file AP_BattMonitor.cpp.
bool AP_BattMonitor::has_current (uint8_t instance) const
has_current - returns true if battery monitor instance provides current info
Definition at line 252 of file AP_BattMonitor.cpp.
Referenced by GCS_MAVLINK::send_battery2(), and GCS_MAVLINK::send_battery_status().
bool AP_BattMonitor::has_current () const inline
Definition at line 101 of file AP_BattMonitor.h.
Referenced by exhausted(), has_current(), and is_powering_off().
bool AP_BattMonitor::healthy (uint8_t instance) const
Definition at line 243 of file AP_BattMonitor.cpp.
bool AP_BattMonitor::healthy (void) const inline
Definition at line 94 of file AP_BattMonitor.h.
Referenced by healthy().
void AP_BattMonitor::init (void)
Definition at line 177 of file AP_BattMonitor.cpp.
Referenced by num_instances(), and setup().
bool AP_BattMonitor::is_powering_off (uint8_t instance) const
Definition at line 247 of file AP_BattMonitor.cpp.
bool AP_BattMonitor::is_powering_off () const inline
Definition at line 97 of file AP_BattMonitor.h.
Referenced by healthy(), and is_powering_off().
uint8_t AP_BattMonitor::num_instances (void) const inline
Definition at line 82 of file AP_BattMonitor.h.
Referenced by AP_Arming::battery_checks(), DataFlash_Class::Log_Write_Current(), GCS_MAVLINK::send_battery2(), and GCS_MAVLINK::send_battery_status().
bool AP_BattMonitor::overpower_detected () const
true when (voltage * current) > watt_max
Definition at line 365 of file AP_BattMonitor.cpp.
Referenced by get_watt_max().
bool AP_BattMonitor::overpower_detected (uint8_t instance) const
Definition at line 374 of file AP_BattMonitor.cpp.
int32_t AP_BattMonitor::pack_capacity_mah (uint8_t instance) const
pack_capacity_mah - returns the capacity of the battery pack in mAh when the pack is full
Definition at line 313 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_Telem::calc_param(), and AP_BattMonitor_Backend::get_capacity().
int32_t AP_BattMonitor::pack_capacity_mah () const inline
Definition at line 126 of file AP_BattMonitor.h.
Referenced by capacity_remaining_pct(), and pack_capacity_mah().
void AP_BattMonitor::read (void)
Read the battery voltage and current for all batteries. Should be called at 10hz.
Definition at line 232 of file AP_BattMonitor.cpp.
Referenced by loop(), and num_instances().
void AP_BattMonitor::set_monitoring (uint8_t instance, uint8_t mon) inline
set_monitoring - sets the monitor type (used for example sketch only)
Definition at line 137 of file AP_BattMonitor.h.
Referenced by setup().
float AP_BattMonitor::voltage (uint8_t instance) const
voltage - returns battery voltage in millivolts
voltage - returns battery voltage in volts
Definition at line 263 of file AP_BattMonitor.cpp.
Referenced by AP_Arming::battery_checks(), AP_Frsky_Telem::calc_batt(), DataFlash_Class::Log_Write_Current(), loop(), GCS_MAVLINK::send_battery2(), AP_Frsky_Telem::send_D(), and AP_Frsky_Telem::send_SPort().
float AP_BattMonitor::voltage () const inline
Definition at line 105 of file AP_BattMonitor.h.
Referenced by has_current(), voltage(), and voltage_resting_estimate().
float AP_BattMonitor::voltage_resting_estimate (uint8_t instance) const
get voltage with sag removed (based on battery current draw and resistance) this will always be greater than or equal to the raw voltage
Definition at line 274 of file AP_BattMonitor.cpp.
Referenced by DataFlash_Class::Log_Write_Current().
float AP_BattMonitor::voltage_resting_estimate () const inline
Definition at line 110 of file AP_BattMonitor.h.
Referenced by exhausted(), voltage(), and voltage_resting_estimate().
Friends And Related Function Documentation
friend class AP_BattMonitor_Analog friend
Definition at line 34 of file AP_BattMonitor.h.
Referenced by init().
friend class AP_BattMonitor_Backend friend
Definition at line 33 of file AP_BattMonitor.h.
friend class AP_BattMonitor_SMBus friend
Definition at line 35 of file AP_BattMonitor.h.
friend class AP_BattMonitor_SMBus_Maxell friend
Definition at line 37 of file AP_BattMonitor.h.
Referenced by init().
friend class AP_BattMonitor_SMBus_Solo friend
Definition at line 36 of file AP_BattMonitor.h.
Referenced by init().
Member Data Documentation
AP_Float AP_BattMonitor::_curr_amp_offset[AP_BATT_MONITOR_MAX_INSTANCES] protected
voltage on current pin multiplied by this to calculate current in amps
Definition at line 170 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor_Analog::read().
AP_Float AP_BattMonitor::_curr_amp_per_volt[AP_BATT_MONITOR_MAX_INSTANCES] protected
voltage on volt pin multiplied by this to calculate battery voltage
Definition at line 169 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor_Analog::read().
AP_Int8 AP_BattMonitor::_curr_pin[AP_BATT_MONITOR_MAX_INSTANCES] protected
board pin used to measure battery voltage
Definition at line 167 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor_Analog::AP_BattMonitor_Analog(), and AP_BattMonitor_Analog::read().
AP_Int8 AP_BattMonitor::_low_voltage_source protected
timeout in seconds before a low voltage event will be triggered
Definition at line 175 of file AP_BattMonitor.h.
Referenced by exhausted().
AP_Int8 AP_BattMonitor::_low_voltage_timeout protected
battery serial number, automatically filled in on SMBus batteries
Definition at line 174 of file AP_BattMonitor.h.
Referenced by exhausted().
AP_Int8 AP_BattMonitor::_monitoring[AP_BATT_MONITOR_MAX_INSTANCES] protected
parameters
Definition at line 165 of file AP_BattMonitor.h.
Referenced by get_type(), has_current(), init(), read(), and set_monitoring().
uint8_t AP_BattMonitor::_num_instances private
Definition at line 180 of file AP_BattMonitor.h.
Referenced by capacity_remaining_pct(), current_amps(), current_total_mah(), exhausted(), has_cell_voltages(), has_current(), healthy(), init(), is_powering_off(), num_instances(), overpower_detected(), read(), voltage(), and voltage_resting_estimate().
AP_Int32 AP_BattMonitor::_pack_capacity[AP_BATT_MONITOR_MAX_INSTANCES] protected
offset voltage that is subtracted from current pin before conversion to amps
Definition at line 171 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor_SMBus::AP_BattMonitor_SMBus(), AP_BattMonitor_Backend::capacity_remaining_pct(), exhausted(), pack_capacity_mah(), and AP_BattMonitor_SMBus::read().
AP_Int32 AP_BattMonitor::_serial_numbers[AP_BATT_MONITOR_MAX_INSTANCES] protected
max battery power allowed. Reduce max throttle to reduce current to satisfy this limit
Definition at line 173 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor_SMBus::AP_BattMonitor_SMBus(), and AP_BattMonitor_SMBus::read().
AP_Float AP_BattMonitor::_volt_multiplier[AP_BATT_MONITOR_MAX_INSTANCES] protected
board pin used to measure battery current
Definition at line 168 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor_Analog::read().
AP_Int8 AP_BattMonitor::_volt_pin[AP_BATT_MONITOR_MAX_INSTANCES] protected
0=disabled, 3=voltage only, 4=voltage and current
Definition at line 166 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor_Analog::AP_BattMonitor_Analog(), and AP_BattMonitor_Analog::read().
AP_Int16 AP_BattMonitor::_watt_max[AP_BATT_MONITOR_MAX_INSTANCES] protected
battery pack capacity less reserve in mAh
Definition at line 172 of file AP_BattMonitor.h.
Referenced by get_watt_max(), and overpower_detected().
AP_BattMonitor_Backend* AP_BattMonitor::drivers[AP_BATT_MONITOR_MAX_INSTANCES] private
Definition at line 179 of file AP_BattMonitor.h.
Referenced by capacity_remaining_pct(), has_cell_voltages(), has_current(), init(), and read().
BattMonitor_State AP_BattMonitor::state[AP_BATT_MONITOR_MAX_INSTANCES] private
voltage type used for detection of low voltage event
Definition at line 178 of file AP_BattMonitor.h.
Referenced by exhausted(), get_cell_voltages(), get_resistance(), get_temperature(), and init().
const AP_Param::GroupInfo AP_BattMonitor::var_info static
Definition at line 160 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor.h
libraries/AP_BattMonitor/AP_BattMonitor.cpp